<?php declare(strict_types=1);

namespace App\ProductModule\Model\ExportToElastic;

class Brands
{

	public const VALUES = [
		'Analergin',
		'Analergin',
		'Diasip',
		'Diasip',
		'Excipial',
		'Excipial',
		'Fortini',
		'Fortini',
		'Isosource',
		'Isosource',
		'Nutridrink',
		'Nutridrink',
		'Nutrilon',
		'Nutrilon',
		'Nutrison',
		'Nutrison',
		'Pangrol',
		'Pangrol',
		'Nestlé',
		'Nestlé',
		'Stacyl',
		'Stacyl',
		'ACC',
		'ACC',
		'Acylpyrin',
		'Acylpyrin',
		'Additiva',
		'Additiva',
		'Aescin',
		'Aescin',
		'ProFarma',
		'ProFarma',
		'Ajatin',
		'Ajatin',
		'Aknecolor',
		'Aknecolor',
		'Allergodil',
		'Allergodil',
		'Leros',
		'Leros',
		'Čajová směs',
		'Čajová směs',
		'Ambrobene',
		'Ambrobene',
		'Anacid',
		'Anacid',
		'APOTEX',
		'APOTEX',
		'Ibuprofen',
		'Ibuprofen',
		'Ascorutin',
		'Ascorutin',
		'Aspirin',
		'Aspirin',
		'Ataralgin',
		'Ataralgin',
		'Aulin',
		'Aulin',
		'BIOMEDICA',
		'BIOMEDICA',
		'Bromhexin',
		'Bromhexin',
		'Bronchipret',
		'Bronchipret',
		'Calcium',
		'Calcium',
		'Caltrate',
		'Caltrate',
		'Candibene',
		'Candibene',
		'Canespor',
		'Canespor',
		'Canesten',
		'Canesten',
		'Carbosorb',
		'Carbosorb',
		'Celaskon',
		'Celaskon',
		'Cholagol',
		'Cholagol',
		'Stada Pharma',
		'Stada Pharma',
		'Coldrex',
		'Coldrex',
		'Condrosulf',
		'Condrosulf',
		'Contractubex',
		'Contractubex',
		'Megafyt',
		'Megafyt',
		'Dettol',
		'Dettol',
		'Ditustat',
		'Ditustat',
		'Drill',
		'Drill',
		'ellaOne',
		'ellaOne',
		'Escapelle',
		'Escapelle',
		'Espumisan',
		'Espumisan',
		'Essentiale',
		'Essentiale',
		'Exoderil',
		'Exoderil',
		'Faktu',
		'Faktu',
		'Fenolax',
		'Fenolax',
		'IBSA',
		'IBSA',
		'Gaviscon',
		'Gaviscon',
		'Geratam',
		'Geratam',
		'Gingio',
		'Gingio',
		'Guajacuran',
		'Guajacuran',
		'Guttalax',
		'Guttalax',
		'Gyno-Pevaryl',
		'Gyno-Pevaryl',
		'Hedelix',
		'Hedelix',
		'Herbadent',
		'Herbadent',
		'Herpesin',
		'Herpesin',
		'Hylak forte',
		'Hylak forte',
		'Ibalgin',
		'Ibalgin',
		'Imazol',
		'Imazol',
		'Imodium',
		'Imodium',
		'Indobene',
		'Indobene',
		'Isochol',
		'Isochol',
		'Jenamazol',
		'Jenamazol',
		'Jox',
		'Jox',
		'Kaloba',
		'Kaloba',
		'Kamistad',
		'Kamistad',
		'Lactulose Al',
		'Lactulose Al',
		'Sandoz',
		'Sandoz',
		'Laxygal',
		'Laxygal',
		'LEVOPRONT',
		'LEVOPRONT',
		'Lioton',
		'Lioton',
		'Livostin',
		'Livostin',
		'Loperon',
		'Loperon',
		'Magne B6',
		'Magne B6',
		'Medicamenta',
		'Medicamenta',
		'Pharmavit',
		'Pharmavit',
		'Mar Rhino',
		'Mar Rhino',
		'Vicks',
		'Vicks',
		'Menofem',
		'Menofem',
		'Migralgin',
		'Migralgin',
		'Milgamma',
		'Milgamma',
		'Mucobene',
		'Mucobene',
		'Mucosolvan',
		'Mucosolvan',
		'Mugotussol',
		'Mugotussol',
		'Nalgesin',
		'Nalgesin',
		'Nasenspray Al',
		'Nasenspray Al',
		'Nasivin',
		'Nasivin',
		'Neo-Angin',
		'Neo-Angin',
		'Neoseptolete',
		'Neoseptolete',
		'Nicorette',
		'Nicorette',
		'Niquitin',
		'Niquitin',
		'Nizoral',
		'Nizoral',
		'Nolpaza',
		'Nolpaza',
		'Novo-Passit',
		'Novo-Passit',
		'Nurofen',
		'Nurofen',
		'Olfen',
		'Olfen',
		'Teva',
		'Teva',
		'Ophthalmo-Septonex',
		'Ophthalmo-Septonex',
		'Orlistat',
		'Orlistat',
		'Panadol',
		'Panadol',
		'Pancreolan',
		'Pancreolan',
		'Paralen',
		'Paralen',
		'Coopharma',
		'Coopharma',
		'Persen',
		'Persen',
		'Pharmatex',
		'Pharmatex',
		'Phlogenzym',
		'Phlogenzym',
		'Pirabene',
		'Pirabene',
		'Piracetam Al',
		'Piracetam Al',
		'Preparation H',
		'Preparation H',
		'Procto-Glyvenol',
		'Procto-Glyvenol',
		'Prostakan',
		'Prostakan',
		'Prostamol',
		'Prostamol',
		'Pyridoxin',
		'Pyridoxin',
		'Rennie',
		'Rennie',
		'Revalid',
		'Revalid',
		'Robitussin',
		'Robitussin',
		'Rosalgin',
		'Rosalgin',
		'Sab Simplex',
		'Sab Simplex',
		'Sanorin',
		'Sanorin',
		'Walmark',
		'Walmark',
		'Septolete',
		'Septolete',
		'Sinex Vicks',
		'Sinex Vicks',
		'Skinoren',
		'Skinoren',
		'Smecta',
		'Smecta',
		'Stodal',
		'Stodal',
		'Stopangin',
		'Stopangin',
		'Stoptussin',
		'Stoptussin',
		'Strepfen',
		'Strepfen',
		'Strepsils',
		'Strepsils',
		'Tantum Verde',
		'Tantum Verde',
		'Tebokan',
		'Tebokan',
		'Thymomel',
		'Thymomel',
		'Traumaplant',
		'Traumaplant',
		'TRAVEL-GUM',
		'TRAVEL-GUM',
		'Tussin',
		'Tussin',
		'Valetol',
		'Valetol',
		'Veral',
		'Veral',
		'Viru-merz',
		'Viru-merz',
		'Visine',
		'Visine',
		'Vitamin E',
		'Vitamin E',
		'Wobenzym',
		'Wobenzym',
		'Xyzal',
		'Xyzal',
		'Zodac',
		'Zodac',
		'Hartmann',
		'Hartmann',
		'Čaj',
		'Čaj',
		'Vectavir',
		'Vectavir',
		'Prospan',
		'Prospan',
		'Iberogast',
		'Iberogast',
		'Arnica Montana',
		'Arnica Montana',
		'Belladonna',
		'Belladonna',
		'Borax',
		'Borax',
		'Chamomila Vulgaris',
		'Chamomila Vulgaris',
		'Euphrasia Officinalis',
		'Euphrasia Officinalis',
		'Rhus Toxicodendron',
		'Rhus Toxicodendron',
		'Vitar',
		'Vitar',
		'Hami',
		'Hami',
		'Aromatica',
		'Aromatica',
		'Gelatina Plus',
		'Gelatina Plus',
		'Rugard',
		'Rugard',
		'Frontline',
		'Frontline',
		'Silvita',
		'Silvita',
		'Herbacos',
		'Herbacos',
		'Geladrink',
		'Geladrink',
		'Intact',
		'Intact',
		'Dr.Popov',
		'Dr.Popov',
		'Lecitamin',
		'Lecitamin',
		'Cetebe',
		'Cetebe',
		'Vincentka',
		'Vincentka',
		'Daylong',
		'Daylong',
		'Zentiva',
		'Zentiva',
		'Driclor',
		'Driclor',
		'BIODERMA',
		'BIODERMA',
		'VICHY',
		'VICHY',
		'Eva',
		'Eva',
		'Meridol',
		'Meridol',
		'Elmex',
		'Elmex',
		'Bübchen',
		'Bübchen',
		'Lepicol',
		'Lepicol',
		'Top Gold',
		'Top Gold',
		'Durex',
		'Durex',
		'Swiss',
		'Swiss',
		'Cannaderm',
		'Cannaderm',
		'Isla',
		'Isla',
		'LA ROCHE-POSAY',
		'LA ROCHE-POSAY',
		'HiPP',
		'HiPP',
		'Elasti-Q',
		'Elasti-Q',
		'Allergan',
		'Allergan',
		'Aconitum Napellus',
		'Aconitum Napellus',
		'Allium Cepa',
		'Allium Cepa',
		'Apis Mellifica',
		'Apis Mellifica',
		'China',
		'China',
		'Nux Vomica',
		'Nux Vomica',
		'Poumon Histamine',
		'Poumon Histamine',
		'Ricinus Communis',
		'Ricinus Communis',
		'Lacalut',
		'Lacalut',
		'Urgo',
		'Urgo',
		'Neutrogena',
		'Neutrogena',
		'Corsodyl',
		'Corsodyl',
		'Farmax',
		'Farmax',
		'Stérimar',
		'Stérimar',
		'Apotheke',
		'Apotheke',
		'BAYER',
		'BAYER',
		'Sarapis',
		'Sarapis',
		'Sebamed',
		'Sebamed',
		'Stada',
		'Stada',
		'Opti Free',
		'Opti Free',
		'Alpecin',
		'Alpecin',
		'Rowatinex',
		'Rowatinex',
		'Fytofontana',
		'Fytofontana',
		'Simply You',
		'Simply You',
		'Barnys',
		'Barnys',
		'GS',
		'GS',
		'Terezia',
		'Terezia',
		'Systane',
		'Systane',
		'BOIRON',
		'BOIRON',
		'Doliva',
		'Doliva',
		'PREDATOR',
		'PREDATOR',
		'MAM',
		'MAM',
		'Priessnitz',
		'Priessnitz',
		'Off',
		'Off',
		'Generica',
		'Generica',
		'Dr.Müller',
		'Dr.Müller',
		'Nisita',
		'Nisita',
		'Altermed',
		'Altermed',
		'Bepanthen',
		'Bepanthen',
		'Vidisic',
		'Vidisic',
		'COMPEED',
		'COMPEED',
		'EUCERIN',
		'EUCERIN',
		'Libenar',
		'Libenar',
		'Curaprox',
		'Curaprox',
		'MaxiMag',
		'MaxiMag',
		'TePe',
		'TePe',
		'Topnatur',
		'Topnatur',
		'Hemodin',
		'Hemodin',
		'Plantur 39',
		'Plantur 39',
		'Linola',
		'Linola',
		'CutisHelp',
		'CutisHelp',
		'Phyteneo',
		'Phyteneo',
		'Dr. Müller Pharma',
		'Dr. Müller Pharma',
		'Optive',
		'Optive',
		'Feminella',
		'Feminella',
		'Revital',
		'Revital',
		'Parodontax',
		'Parodontax',
		'Ocuvite',
		'Ocuvite',
		'Ladival',
		'Ladival',
		'Physiomer',
		'Physiomer',
		'Septonex',
		'Septonex',
		'Glim Care',
		'Glim Care',
		'DiaChrom',
		'DiaChrom',
		'Listerine',
		'Listerine',
		'Centrum',
		'Centrum',
		'Aloclair',
		'Aloclair',
		'Kneipp',
		'Kneipp',
		'Panthenol',
		'Panthenol',
		'Quixx',
		'Quixx',
		'Humer',
		'Humer',
		'Sensodyne',
		'Sensodyne',
		'Cyndicate',
		'Cyndicate',
		'Calgel',
		'Calgel',
		'Actinica',
		'Actinica',
		'Valosun',
		'Valosun',
		'Paranit',
		'Paranit',
		'Dr.Böhm',
		'Dr.Böhm',
		'Fructolax',
		'Fructolax',
		'Infacol',
		'Infacol',
		'Neocapil',
		'Neocapil',
		'Sunárek',
		'Sunárek',
		'Junior-angin',
		'Junior-angin',
		'Corega',
		'Corega',
		'Swissdent',
		'Swissdent',
		'XL-S Medical',
		'XL-S Medical',
		'Swiss NatureVia',
		'Swiss NatureVia',
		'3M',
		'3M',
		'Allga San',
		'Allga San',
		'Vibovit',
		'Vibovit',
		'Nailexpert',
		'Nailexpert',
		'Zdrovit',
		'Zdrovit',
		'Hyabak',
		'Hyabak',
		'Wartner',
		'Wartner',
		'Oscillococcinum',
		'Oscillococcinum',
		'Salus',
		'Salus',
		'Diosminol',
		'Diosminol',
		'BENU',
		'BENU',
		'Lactofeel',
		'Lactofeel',
		'Chytré miminko',
		'Chytré miminko',
		'Prevenzym W',
		'Prevenzym W',
		'Supradyn',
		'Supradyn',
		'Weleda',
		'Weleda',
		'Herbo Medica',
		'Herbo Medica',
		'Ocutein',
		'Ocutein',
		'Protefix',
		'Protefix',
		'Energit',
		'Energit',
		'MultiIMUN',
		'MultiIMUN',
		'Dr. Cann',
		'Dr. Cann',
		'Dehinel',
		'Dehinel',
		'NATUREVIA',
		'NATUREVIA',
		'Inofolic',
		'Inofolic',
		'Sunar',
		'Sunar',
		'Fypryst',
		'Fypryst',
		'Dapis',
		'Dapis',
		'CLAVIN',
		'CLAVIN',
		'Sunarka',
		'Sunarka',
		'Oralflux',
		'Oralflux',
		'BioGaia',
		'BioGaia',
		'Fytofem',
		'Fytofem',
		'Bi-Oil',
		'Bi-Oil',
		'Cemio',
		'Cemio',
		'Dr. Müller',
		'Dr. Müller',
		'ESTHEDERM',
		'ESTHEDERM',
		'Laxafruit',
		'Laxafruit',
		'Blokurima',
		'Blokurima',
		'Dexoket',
		'Dexoket',
		'HemoClin',
		'HemoClin',
		'PoxClin',
		'PoxClin',
		'Ixoderm',
		'Ixoderm',
		'Forfemina',
		'Forfemina',
		'Lactacyd',
		'Lactacyd',
		'Voice angin',
		'Voice angin',
		'Sprej',
		'Sprej',
		'Blend-a-dent',
		'Blend-a-dent',
		'Colafit',
		'Colafit',
		'Dr.Konrad',
		'Dr.Konrad',
		'PET HEALTH CARE',
		'PET HEALTH CARE',
		'Sudocrem',
		'Sudocrem',
		'Wurm-Ex',
		'Wurm-Ex',
		'FOLANDROL',
		'FOLANDROL',
		'Nutrimama',
		'Nutrimama',
		'Avilut',
		'Avilut',
		'PharmaSwiss',
		'PharmaSwiss',
		'UniCare',
		'UniCare',
		'Algesal',
		'Algesal',
		'Drill růžový med',
		'Drill růžový med',
		'Gool',
		'Gool',
		'Piracetam',
		'Piracetam',
		'Hydrastis Canadensis',
		'Hydrastis Canadensis',
		'Protifar',
		'Protifar',
		'Graphites',
		'Graphites',
		'Clogin',
		'Clogin',
		'Plantur21',
		'Plantur21',
		'Fagron',
		'Fagron',
		'Ceumed',
		'Ceumed',
		'Kapsaicinová náplast',
		'Kapsaicinová náplast',
		'Sanova',
		'Sanova',
		'Caniverm',
		'Caniverm',
		'Zajíc',
		'Zajíc',
		'Traubenzucker Lolly',
		'Traubenzucker Lolly',
		'Naturvita',
		'Naturvita',
		'BabyCalm',
		'BabyCalm',
		'Imunoglukan',
		'Imunoglukan',
		'Ovosan',
		'Ovosan',
		'UNIMED PHARMA',
		'UNIMED PHARMA',
		'Health link',
		'Health link',
		'Favea',
		'Favea',
		'Australian Bodycare',
		'Australian Bodycare',
		'Hylo',
		'Hylo',
		'Biodeur',
		'Biodeur',
		'ACUTIL',
		'ACUTIL',
		'Selzink',
		'Selzink',
		'Eye q',
		'Eye q',
		'Temtex',
		'Temtex',
		'Esprico',
		'Esprico',
		'Vitabalans',
		'Vitabalans',
		'Arianna',
		'Arianna',
		'Imedeen',
		'Imedeen',
		'Brainway',
		'Brainway',
		'Varumin',
		'Varumin',
		'TENA',
		'TENA',
		'Steriwund',
		'Steriwund',
		'Indonal',
		'Indonal',
		'Stepar',
		'Stepar',
		'Alpa',
		'Alpa',
		'SKIN-CAP',
		'SKIN-CAP',
		'Spofavit',
		'Spofavit',
		'No-Prostal',
		'No-Prostal',
		'Regina',
		'Regina',
		'Biohar',
		'Biohar',
		'MedPharma',
		'MedPharma',
		'Pharma Nord',
		'Pharma Nord',
		'AVICENNA',
		'AVICENNA',
		'Gelmodel',
		'Gelmodel',
		'PM',
		'PM',
		'CICATRIDINA',
		'CICATRIDINA',
		'Pangamin',
		'Pangamin',
		'Vitagyn C',
		'Vitagyn C',
		'Recugel',
		'Recugel',
		'Farmex',
		'Farmex',
		'Herbamedicus',
		'Herbamedicus',
		'Missiva',
		'Missiva',
		'Acnevac',
		'Acnevac',
		'PharmaSuisse',
		'PharmaSuisse',
		'Biogena',
		'Biogena',
		'TOPVET',
		'TOPVET',
		'BlueCap',
		'BlueCap',
		'Clearblue',
		'Clearblue',
		'Magnetrans',
		'Magnetrans',
		'Clinical',
		'Clinical',
		'Alfa Vita',
		'Alfa Vita',
		'Kolostrum',
		'Kolostrum',
		'Nasodrill',
		'Nasodrill',
		'Virasoothe',
		'Virasoothe',
		'Gynocaps',
		'Gynocaps',
		'Exadipin',
		'Exadipin',
		'Bifolac',
		'Bifolac',
		'Diorex',
		'Diorex',
		'Nasil',
		'Nasil',
		'Hedrin',
		'Hedrin',
		'Diovarix',
		'Diovarix',
		'Neuritogen',
		'Neuritogen',
		'VULM',
		'VULM',
		'Herbex',
		'Herbex',
		'ImunoBran',
		'ImunoBran',
		'Almirall',
		'Almirall',
		'GLIDE 4you',
		'GLIDE 4you',
		'Darvit',
		'Darvit',
		'Candivac',
		'Candivac',
		'PROfertil',
		'PROfertil',
		'Nature\'s Bounty Zinek',
		'Nature\'s Bounty Zinek',
		'GLO',
		'GLO',
		'Vaxol',
		'Vaxol',
		'ProfiChondro',
		'ProfiChondro',
		'Seni',
		'Seni',
		'Calcitral',
		'Calcitral',
		'Multi-Gyn',
		'Multi-Gyn',
		'Bio panenský kokosový olej',
		'Bio panenský kokosový olej',
		'Omron',
		'Omron',
		'Perlan',
		'Perlan',
		'Maltoferrochin',
		'Maltoferrochin',
		'Refit',
		'Refit',
		'Anti-Stress',
		'Anti-Stress',
		'Ryor',
		'Ryor',
		'Dexeryl',
		'Dexeryl',
		'DI-PROSTAN',
		'DI-PROSTAN',
		'ReNu',
		'ReNu',
		'Saforelle',
		'Saforelle',
		'AQUA ANNA',
		'AQUA ANNA',
		'Vitella',
		'Vitella',
		'Urivac',
		'Urivac',
		'OmegaDefend',
		'OmegaDefend',
		'Woman secret BABY',
		'Woman secret BABY',
		'Betaglukan',
		'Betaglukan',
		'Conceive',
		'Conceive',
		'JML',
		'JML',
		'SCHOLL',
		'SCHOLL',
		'Rej',
		'Rej',
		'Johnson\'s',
		'Johnson\'s',
		'Annabis',
		'Annabis',
		'Folaxan',
		'Folaxan',
		'KAPRONA',
		'KAPRONA',
		'Express diet',
		'Express diet',
		'Cantalin',
		'Cantalin',
		'Zaječická hořká',
		'Zaječická hořká',
		'Halls',
		'Halls',
		'Aviril',
		'Aviril',
		'FytoPharma',
		'FytoPharma',
		'Šaratica',
		'Šaratica',
		'Urocont',
		'Urocont',
		'Mogador',
		'Mogador',
		'Dr. Landa',
		'Dr. Landa',
		'Natural Medicaments',
		'Natural Medicaments',
		'Mediket',
		'Mediket',
		'Spark plugs',
		'Spark plugs',
		'ALAVIS',
		'ALAVIS',
		'Virde',
		'Virde',
		'PharmaLINE',
		'PharmaLINE',
		'Kompava',
		'Kompava',
		'DMAE',
		'DMAE',
		'Remedicum',
		'Remedicum',
		'Ostrovidky',
		'Ostrovidky',
		'Nutricius',
		'Nutricius',
		'Tým pro farmacii',
		'Tým pro farmacii',
		'Ginexid',
		'Ginexid',
		'NaturGYN Scarlett',
		'NaturGYN Scarlett',
		'Fertilan',
		'Fertilan',
		'Dr. Bojda',
		'Dr. Bojda',
		'Fertility Blend',
		'Fertility Blend',
		'Diohes',
		'Diohes',
		'Poex',
		'Poex',
		'SCHERING-PLOUGH',
		'SCHERING-PLOUGH',
		'Kolagen FORTE',
		'Kolagen FORTE',
		'MegaSmile',
		'MegaSmile',
		'Aptus',
		'Aptus',
		'Reparex',
		'Reparex',
		'Revitanerv',
		'Revitanerv',
		'White Pearl',
		'White Pearl',
		'Wörwag Pharma',
		'Wörwag Pharma',
		'Evelle',
		'Evelle',
		'Viprosal B',
		'Viprosal B',
		'MenoMax',
		'MenoMax',
		'Probi Aktiv',
		'Probi Aktiv',
		'Akutol',
		'Akutol',
		'Liftea',
		'Liftea',
		'Pampers',
		'Pampers',
		'Daosin',
		'Daosin',
		'Pharma Activ',
		'Pharma Activ',
		'Merco',
		'Merco',
		'Vřídlo',
		'Vřídlo',
		'Irbis',
		'Irbis',
		'Olimpex',
		'Olimpex',
		'Pectol',
		'Pectol',
		'Oral-B',
		'Oral-B',
		'NUTREND',
		'NUTREND',
		'Nefdesanté',
		'Nefdesanté',
		'Fructal',
		'Fructal',
		'FC',
		'FC',
		'Spagyria',
		'Spagyria',
		'Dermatix',
		'Dermatix',
		'Allivictus',
		'Allivictus',
		'Sililevo',
		'Sililevo',
		'Bio-Kult',
		'Bio-Kult',
		'Ducray',
		'Ducray',
		'ellen',
		'ellen',
		'Percom',
		'Percom',
		'2DERM',
		'2DERM',
		'Vieste',
		'Vieste',
		'ATIX',
		'ATIX',
		'OBZOR',
		'OBZOR',
		'Original silicea balsam',
		'Original silicea balsam',
		'Vitadiet',
		'Vitadiet',
		'Guareta',
		'Guareta',
		'Carbofit',
		'Carbofit',
		'Enterosgel',
		'Enterosgel',
		'Nature\'s Bounty',
		'Nature\'s Bounty',
		'Sunpharm',
		'Sunpharm',
		'Medicprogress',
		'Medicprogress',
		'AVENT',
		'AVENT',
		'Pharma Future',
		'Pharma Future',
		'Dermaguard',
		'Dermaguard',
		'Nature´s Bounty',
		'Nature´s Bounty',
		'Ginseng royal',
		'Ginseng royal',
		'Trolli',
		'Trolli',
		'Medela',
		'Medela',
		'Herpclair',
		'Herpclair',
		'GASTROTUSS',
		'GASTROTUSS',
		'Tasectan',
		'Tasectan',
		'PROKTIS-M',
		'PROKTIS-M',
		'Woykoff',
		'Woykoff',
		'Jamieson',
		'Jamieson',
		'CEM-M',
		'CEM-M',
		'GelActiv',
		'GelActiv',
		'Labofarm',
		'Labofarm',
		'Teekanne',
		'Teekanne',
		'VitaHarmony',
		'VitaHarmony',
		'Kulíšek',
		'Kulíšek',
		'Unilakt',
		'Unilakt',
		'Cryos',
		'Cryos',
		'Noventis',
		'Noventis',
		'TheraTech',
		'TheraTech',
		'Goldim',
		'Goldim',
		'GelitaSpon',
		'GelitaSpon',
		'Arkopharma',
		'Arkopharma',
		'NástrojeZdraví',
		'NástrojeZdraví',
		'Rosen Pharma',
		'Rosen Pharma',
		'VAGILACT',
		'VAGILACT',
		'Sayonara',
		'Sayonara',
		'Dr.Theiss',
		'Dr.Theiss',
		'Bolfo',
		'Bolfo',
		'Ryorex',
		'Ryorex',
		'Akacia',
		'Akacia',
		'Dětský artikl a Hračky s cukrovinkou',
		'Dětský artikl a Hračky s cukrovinkou',
		'Vagisan',
		'Vagisan',
		'Natura',
		'Natura',
		'Ozalin',
		'Ozalin',
		'Jizerské pekárny',
		'Jizerské pekárny',
		'Ecolab',
		'Ecolab',
		'Medistik',
		'Medistik',
		'Linex',
		'Linex',
		'ADVANCE',
		'ADVANCE',
		'Glenmark',
		'Glenmark',
		'Emspoma',
		'Emspoma',
		'Koalka',
		'Koalka',
		'Menoflavon',
		'Menoflavon',
		'ARPALIT',
		'ARPALIT',
		'SPEED 8',
		'SPEED 8',
		'Lesklokorka lesklá',
		'Lesklokorka lesklá',
		'Iskial',
		'Iskial',
		'Ferda Mix',
		'Ferda Mix',
		'Medisana',
		'Medisana',
		'Pythie',
		'Pythie',
		'Good Nature',
		'Good Nature',
		'Orthomol',
		'Orthomol',
		'Chocopharm',
		'Chocopharm',
		'Dest Pharm',
		'Dest Pharm',
		'Probio-Fix',
		'Probio-Fix',
		'Herbalon',
		'Herbalon',
		'Fytoprost',
		'Fytoprost',
		'Celsius',
		'Celsius',
		'Batist',
		'Batist',
		'Lactovita',
		'Lactovita',
		'Nutrolin-B',
		'Nutrolin-B',
		'Lutamax',
		'Lutamax',
		'Ricola',
		'Ricola',
		'Microlife',
		'Microlife',
		'JODIS',
		'JODIS',
		'Sinupo Forte',
		'Sinupo Forte',
		'Rotinal',
		'Rotinal',
		'E.A.R.Classic',
		'E.A.R.Classic',
		'Desprej',
		'Desprej',
		'Propolis',
		'Propolis',
		'Chicco',
		'Chicco',
		'Doer medical',
		'Doer medical',
		'Pearls',
		'Pearls',
		'Babystart',
		'Babystart',
		'Blephasol',
		'Blephasol',
		'Chondrocan',
		'Chondrocan',
		'Pro-Visio',
		'Pro-Visio',
		'E.A.R.Comfort',
		'E.A.R.Comfort',
		'Fan',
		'Fan',
		'Colostrum',
		'Colostrum',
		'Svorto',
		'Svorto',
		'Parasidose',
		'Parasidose',
		'Silymarin',
		'Silymarin',
		'Body Tip',
		'Body Tip',
		'Delmar',
		'Delmar',
		'Diavita',
		'Diavita',
		'Symbiotics',
		'Symbiotics',
		'Abena',
		'Abena',
		'Chilly',
		'Chilly',
		'Opti-Free',
		'Opti-Free',
		'Hemann',
		'Hemann',
		'Grešík',
		'Grešík',
		'KineMAX',
		'KineMAX',
		'AMPcare',
		'AMPcare',
		'Trioderm',
		'Trioderm',
		'Avene',
		'Avene',
		'Intim Comfort',
		'Intim Comfort',
		'Lactolady',
		'Lactolady',
		'Durissus',
		'Durissus',
		'BioMagick',
		'BioMagick',
		'Vitage',
		'Vitage',
		'RapiClear',
		'RapiClear',
		'Oralmedic',
		'Oralmedic',
		'Barekol',
		'Barekol',
		'Miraclean',
		'Miraclean',
		'Ohropax',
		'Ohropax',
		'Batavan',
		'Batavan',
		'Fox',
		'Fox',
		'ENTERINA',
		'ENTERINA',
		'Exatherm',
		'Exatherm',
		'Bioveta',
		'Bioveta',
		'Pharmacy Laboratories',
		'Pharmacy Laboratories',
		'BABY NOVA',
		'BABY NOVA',
		'Kofein K',
		'Kofein K',
		'Linteo',
		'Linteo',
		'Natures Aid',
		'Natures Aid',
		'Ekomedica',
		'Ekomedica',
		'GELACET',
		'GELACET',
		'NUK',
		'NUK',
		'GUNA',
		'GUNA',
		'Stevia',
		'Stevia',
		'Prontosan',
		'Prontosan',
		'Artrofit',
		'Artrofit',
		'Torf-Ziegler',
		'Torf-Ziegler',
		'RAPETO',
		'RAPETO',
		'Nominal',
		'Nominal',
		'Strataderm',
		'Strataderm',
		'Niacin',
		'Niacin',
		'Triphala',
		'Triphala',
		'Natures',
		'Natures',
		'Thealoz Duo',
		'Thealoz Duo',
		'Enzymel',
		'Enzymel',
		'CUKROPUR',
		'CUKROPUR',
		'B17 Preventum',
		'B17 Preventum',
		'PREVAPIS',
		'PREVAPIS',
		'EUBIOMED',
		'EUBIOMED',
		'Caffit',
		'Caffit',
		'ISOSTAR',
		'ISOSTAR',
		'HERBAVERA',
		'HERBAVERA',
		'Aplefit',
		'Aplefit',
		'PEDIAKID',
		'PEDIAKID',
		'Fertiprona',
		'Fertiprona',
		'Flavobion',
		'Flavobion',
		'Four Seasons',
		'Four Seasons',
		'Anticol',
		'Anticol',
		'Natural Factors',
		'Natural Factors',
		'Parontal',
		'Parontal',
		'MedinTerra',
		'MedinTerra',
		'Ascoffin',
		'Ascoffin',
		'OCUflash',
		'OCUflash',
		'Diaskor',
		'Diaskor',
		'Biocard',
		'Biocard',
		'MAURERS',
		'MAURERS',
		'Křemík',
		'Křemík',
		'Capissan',
		'Capissan',
		'Evelor',
		'Evelor',
		'Biotta',
		'Biotta',
		'LactaNON',
		'LactaNON',
		'Saloos',
		'Saloos',
		'Kiltix',
		'Kiltix',
		'Kurkumin',
		'Kurkumin',
		'Equazen',
		'Equazen',
		'Rulcotherapy',
		'Rulcotherapy',
		'Celimed',
		'Celimed',
		'Mediflex Duo',
		'Mediflex Duo',
		'NaturaWay',
		'NaturaWay',
		'Konopné mazání',
		'Konopné mazání',
		'Biofreeze',
		'Biofreeze',
		'Codefree',
		'Codefree',
		'DestPharm',
		'DestPharm',
		'Reproman',
		'Reproman',
		'Olivocap',
		'Olivocap',
		'Sanitas',
		'Sanitas',
		'Pure',
		'Pure',
		'Vivil',
		'Vivil',
		'Happy Pills',
		'Happy Pills',
		'Elimax',
		'Elimax',
		'Vulkan',
		'Vulkan',
		'ZSZ',
		'ZSZ',
		'Capimin',
		'Capimin',
		'Olimunovac',
		'Olimunovac',
		'BTC Invest',
		'BTC Invest',
		'Fishermans Friend',
		'Fishermans Friend',
		'Altest',
		'Altest',
		'Erba Lachema',
		'Erba Lachema',
		'Kávoviny',
		'Kávoviny',
		'Koenzym Q10',
		'Koenzym Q10',
		'Easylax',
		'Easylax',
		'A-Derma',
		'A-Derma',
		'MEDICALFOX',
		'MEDICALFOX',
		'Omega 3',
		'Omega 3',
		'English Tea Shop',
		'English Tea Shop',
		'Sebclair',
		'Sebclair',
		'IVT',
		'IVT',
		'Instant View',
		'Instant View',
		'Blistex',
		'Blistex',
		'DietLine',
		'DietLine',
		'Cryoflex',
		'Cryoflex',
		'Neostrata',
		'Neostrata',
		'TeaTao',
		'TeaTao',
		'Relikt AE',
		'Relikt AE',
		'Naturell',
		'Naturell',
		'Kitl',
		'Kitl',
		'Biora',
		'Biora',
		'Biogama',
		'Biogama',
		'CandyS',
		'CandyS',
		'Bioster',
		'Bioster',
		'INDOL-IN',
		'INDOL-IN',
		'Monoderma',
		'Monoderma',
		'Epaderm',
		'Epaderm',
		'Jezevčí mast',
		'Jezevčí mast',
		'Arnigel',
		'Arnigel',
		'Pro-Visio Forte',
		'Pro-Visio Forte',
		'Arthrobalans',
		'Arthrobalans',
		'Natusweet',
		'Natusweet',
		'Top Test baby',
		'Top Test baby',
		'Edenpharma',
		'Edenpharma',
		'Celius',
		'Celius',
		'Matchatea',
		'Matchatea',
		'Spofaplast',
		'Spofaplast',
		'Vittela',
		'Vittela',
		'Motherlove',
		'Motherlove',
		'Dologel',
		'Dologel',
		'Hyalfit',
		'Hyalfit',
		'Beurer',
		'Beurer',
		'Solgar',
		'Solgar',
		'NOLLIX',
		'NOLLIX',
		'Allnature',
		'Allnature',
		'Lipobase Repair',
		'Lipobase Repair',
		'Epigen',
		'Epigen',
		'Tea Tao',
		'Tea Tao',
		'Nasodren',
		'Nasodren',
		'Labello',
		'Labello',
		'Sanytol',
		'Sanytol',
		'Vakos XT',
		'Vakos XT',
		'Lirene',
		'Lirene',
		'Dermacol',
		'Dermacol',
		'Visocor',
		'Visocor',
		'Imugamin Effective',
		'Imugamin Effective',
		'Naturprodukt',
		'Naturprodukt',
		'Labeta',
		'Labeta',
		'Santée',
		'Santée',
		'Polenal Forte',
		'Polenal Forte',
		'PHARMACY',
		'PHARMACY',
		'Condurango',
		'Condurango',
		'Bílinská kyselka',
		'Bílinská kyselka',
		'Orling',
		'Orling',
		'Apoteka',
		'Apoteka',
		'Eveline',
		'Eveline',
		'Unios Pharma',
		'Unios Pharma',
		'OraQuick',
		'OraQuick',
		'DERMAPRO',
		'DERMAPRO',
		'Protopan',
		'Protopan',
		'GemiOptal',
		'GemiOptal',
		'Sorion',
		'Sorion',
		'Innova Pharma',
		'Innova Pharma',
		'Stratamark',
		'Stratamark',
		'o.b.',
		'o.b.',
		'WATER JEL',
		'WATER JEL',
		'Klorane',
		'Klorane',
		'VitaSmart',
		'VitaSmart',
		'Australian',
		'Australian',
		'Naturmoor',
		'Naturmoor',
		'Relikt',
		'Relikt',
		'Kubík',
		'Kubík',
		'PARIN-POS',
		'PARIN-POS',
		'Plastifon',
		'Plastifon',
		'Lomatuell',
		'Lomatuell',
		'Apa Care',
		'Apa Care',
		'Scar Esthetique',
		'Scar Esthetique',
		'Handsafe',
		'Handsafe',
		'KAWAR',
		'KAWAR',
		'AKH',
		'AKH',
		'Aleeda',
		'Aleeda',
		'PresiDENT',
		'PresiDENT',
		'Laktazan',
		'Laktazan',
		'Nutrisante',
		'Nutrisante',
		'Elancyl',
		'Elancyl',
		'DR.DUDEK',
		'DR.DUDEK',
		'Sabi Intim',
		'Sabi Intim',
		'Thrombexin',
		'Thrombexin',
		'Drogerex',
		'Drogerex',
		'Enticon',
		'Enticon',
		'Nutricia',
		'Nutricia',
		'Kinedryl',
		'Kinedryl',
		'RESCUE',
		'RESCUE',
		'SUPP.GLYCERINI SANOVA',
		'SUPP.GLYCERINI SANOVA',
		'Aquacel',
		'Aquacel',
		'Viacell',
		'Viacell',
		'PruriGyne',
		'PruriGyne',
		'Wellion',
		'Wellion',
		'Tradenet',
		'Tradenet',
		'MEDIDOS',
		'MEDIDOS',
		'Dr.Méďa',
		'Dr.Méďa',
		'Mastiha Therapy',
		'Mastiha Therapy',
		'ORITOLIN',
		'ORITOLIN',
		'Bio-pharma',
		'Bio-pharma',
		'Diagnostic',
		'Diagnostic',
		'Aspecton',
		'Aspecton',
		'Cofi tabs',
		'Cofi tabs',
		'Harpago',
		'Harpago',
		'Fix',
		'Fix',
		'Halset',
		'Halset',
		'Dixi',
		'Dixi',
		'Novalim',
		'Novalim',
		'Chiraskin',
		'Chiraskin',
		'Duracell',
		'Duracell',
		'OsteoK2',
		'OsteoK2',
		'Gelacan',
		'Gelacan',
		'Diet Esthetic',
		'Diet Esthetic',
		'Beaphar',
		'Beaphar',
		'Nagyn',
		'Nagyn',
		'Sanct Bernhard',
		'Sanct Bernhard',
		'SD Codefree',
		'SD Codefree',
		'Aspenzym',
		'Aspenzym',
		'Marnys',
		'Marnys',
		'VivaPharm',
		'VivaPharm',
		'Pythie Biogama',
		'Pythie Biogama',
		'Kin',
		'Kin',
		'Stratamed',
		'Stratamed',
		'Calcidrink',
		'Calcidrink',
		'StrataXRT',
		'StrataXRT',
		'Dermedic',
		'Dermedic',
		'ActivLab',
		'ActivLab',
		'SilverCare',
		'SilverCare',
		'Mask',
		'Mask',
		'Indulona',
		'Indulona',
		'Haas',
		'Haas',
		'Anginal',
		'Anginal',
		'BABIO',
		'BABIO',
		'SynCare',
		'SynCare',
		'GUARANAPLUS',
		'GUARANAPLUS',
		'Arterin',
		'Arterin',
		'Oparstop',
		'Oparstop',
		'Dalli Med',
		'Dalli Med',
		'Pharma Grade',
		'Pharma Grade',
		'J.D.S.',
		'J.D.S.',
		'Befoli',
		'Befoli',
		'Philips',
		'Philips',
		'Bioclin',
		'Bioclin',
		'Soloceryl',
		'Soloceryl',
		'Nivea',
		'Nivea',
		'Bio Block',
		'Bio Block',
		'Okopharm',
		'Okopharm',
		'Epam',
		'Epam',
		'AlfaVita',
		'AlfaVita',
		'Vasogen',
		'Vasogen',
		'Bio Bachovky',
		'Bio Bachovky',
		'Humana',
		'Humana',
		'H2Out',
		'H2Out',
		'Sulfothion',
		'Sulfothion',
		'DR. GREPL',
		'DR. GREPL',
		'Hannasaki',
		'Hannasaki',
		'Modom',
		'Modom',
		'ARES',
		'ARES',
		'RejuvaSil',
		'RejuvaSil',
		'Antimetil',
		'Antimetil',
		'Canpol babies',
		'Canpol babies',
		'Inca collagen',
		'Inca collagen',
		'Stopfiltr',
		'Stopfiltr',
		'Obezin',
		'Obezin',
		'Dermolaval',
		'Dermolaval',
		'Geratherm',
		'Geratherm',
		'Catalysis',
		'Catalysis',
		'Maxis',
		'Maxis',
		'Difa Cooper',
		'Difa Cooper',
		'Benkor',
		'Benkor',
		'Sam Mills',
		'Sam Mills',
		'Tretterś Chips',
		'Tretterś Chips',
		'Pravé hořické trubičky',
		'Pravé hořické trubičky',
		'Little Angel',
		'Little Angel',
		'Hors',
		'Hors',
		'Semix',
		'Semix',
		'Rudolfův pramen',
		'Rudolfův pramen',
		'Remescar',
		'Remescar',
		'Standart Diagnostics',
		'Standart Diagnostics',
		'Gymy',
		'Gymy',
		'JOYCARE',
		'JOYCARE',
		'Sodermix',
		'Sodermix',
		'Gillette',
		'Gillette',
		'Prokardin',
		'Prokardin',
		'Čajánek',
		'Čajánek',
		'Exacto',
		'Exacto',
		'Fytos',
		'Fytos',
		'Vetrisol',
		'Vetrisol',
		'Claritine',
		'Claritine',
		'Atopiclair',
		'Atopiclair',
		'Glatte',
		'Glatte',
		'Regaine',
		'Regaine',
		'Golden Zlaté pastilky',
		'Golden Zlaté pastilky',
		'Zitenax',
		'Zitenax',
		'ALFASILVER',
		'ALFASILVER',
		'Probacin',
		'Probacin',
		'Hydrokortison',
		'Hydrokortison',
		'Enterol',
		'Enterol',
		'Elanatura',
		'Elanatura',
		'Piz Buin',
		'Piz Buin',
		'Brufen',
		'Brufen',
		'HIMALYO',
		'HIMALYO',
		'Rinopanteina',
		'Rinopanteina',
		'Cetaphil',
		'Cetaphil',
		'Vescor',
		'Vescor',
		'Discreet',
		'Discreet',
		'Naturella',
		'Naturella',
		'Always',
		'Always',
		'Blend-a-med',
		'Blend-a-med',
		'Dr.Gaye',
		'Dr.Gaye',
		'Zendium',
		'Zendium',
		'Vividrin',
		'Vividrin',
		'Energy',
		'Energy',
		'Sun Vital',
		'Sun Vital',
		'Astrid',
		'Astrid',
		'Garnier',
		'Garnier',
		'Alcon',
		'Alcon',
		'SAMBUCOL',
		'SAMBUCOL',
		'Huggies',
		'Huggies',
		'Parazitex',
		'Parazitex',
		'Isis Pharma',
		'Isis Pharma',
		'Fiprotec',
		'Fiprotec',
		'Depend',
		'Depend',
		'Freeman',
		'Freeman',
		'Druid',
		'Druid',
		'PHARCOS',
		'PHARCOS',
		'CARUN',
		'CARUN',
		'Salcura',
		'Salcura',
		'GS Vitamin C',
		'GS Vitamin C',
		'Perspirex',
		'Perspirex',
		'Fora',
		'Fora',
		'Accu Chek',
		'Accu Chek',
		'GlucoLab',
		'GlucoLab',
		'Dragon Power',
		'Dragon Power',
		'Edel White',
		'Edel White',
		'Linkus',
		'Linkus',
		'Parexyl',
		'Parexyl',
		'Apomedica',
		'Apomedica',
		'Viva Pharm',
		'Viva Pharm',
		'Bodi-tek',
		'Bodi-tek',
		'ESI',
		'ESI',
		'Rio Dental Polisher',
		'Rio Dental Polisher',
		'Mollers',
		'Mollers',
		'Matis Paris',
		'Matis Paris',
		'Marimer',
		'Marimer',
		'Vetericyn',
		'Vetericyn',
		'Nef de Santé',
		'Nef de Santé',
		'OneTouch',
		'OneTouch',
		'LA CHEVRE',
		'LA CHEVRE',
		'Colgate',
		'Colgate',
		'Farlin',
		'Farlin',
		'Clipper',
		'Clipper',
		'Venufit',
		'Venufit',
		'Milford',
		'Milford',
		'Glucocard',
		'Glucocard',
		'Shuya',
		'Shuya',
		'Healing nature',
		'Healing nature',
		'Kaiser',
		'Kaiser',
		'Ecodenta',
		'Ecodenta',
		'Green Apotheke',
		'Green Apotheke',
		'Vitango',
		'Vitango',
		'Solingen',
		'Solingen',
		'Imperial Vitamins',
		'Imperial Vitamins',
		'Suavinex',
		'Suavinex',
		'Quasix',
		'Quasix',
		'Rio',
		'Rio',
		'Mastic Life',
		'Mastic Life',
		'Link Natural Products',
		'Link Natural Products',
		'Sudantha',
		'Sudantha',
		'Samahan',
		'Samahan',
		'WUNDmed',
		'WUNDmed',
		'Bright starts',
		'Bright starts',
		'Nature´s Answers',
		'Nature´s Answers',
		'Betadine',
		'Betadine',
		'IREL',
		'IREL',
		'Migliorin',
		'Migliorin',
		'Cosval',
		'Cosval',
		'Mamavis',
		'Mamavis',
		'Naturfakt',
		'Naturfakt',
		'Compliflora',
		'Compliflora',
		'Cecemed',
		'Cecemed',
		'Cimmerin',
		'Cimmerin',
		'Cognoscin',
		'Cognoscin',
		'Cigir Kymia',
		'Cigir Kymia',
		'MAGNEROT',
		'MAGNEROT',
		'Livermed',
		'Livermed',
		'DeflaGyn',
		'DeflaGyn',
		'Belupo',
		'Belupo',
		'Day Spa',
		'Day Spa',
		'Livol',
		'Livol',
		'Propanthen',
		'Propanthen',
		'Panzytrat',
		'Panzytrat',
		'Mesoft',
		'Mesoft',
		'Septilen',
		'Septilen',
		'Gama',
		'Gama',
		'Mepore',
		'Mepore',
		'FertilMan',
		'FertilMan',
		'Diacontrol',
		'Diacontrol',
		'Epicomed',
		'Epicomed',
		'Gelita-Spon',
		'Gelita-Spon',
		'Matopat',
		'Matopat',
		'Gynostemma',
		'Gynostemma',
		'iD',
		'iD',
		'Mont Blanc',
		'Mont Blanc',
		'Mueller',
		'Mueller',
		'Adiel',
		'Adiel',
		'Manitera pharma',
		'Manitera pharma',
		'Axonia',
		'Axonia',
		'Buccotherm',
		'Buccotherm',
		'Juvena',
		'Juvena',
		'GUM',
		'GUM',
		'Zlatý doušek',
		'Zlatý doušek',
		'For Merco',
		'For Merco',
		'Vita',
		'Vita',
		'Clerex',
		'Clerex',
		'Bio Pharma',
		'Bio Pharma',
		'Steriko',
		'Steriko',
		'Alaska',
		'Alaska',
		'Vita-Pos',
		'Vita-Pos',
		'Garganta',
		'Garganta',
		'Duphalac',
		'Duphalac',
		'Agetis',
		'Agetis',
		'Emco',
		'Emco',
		'Bersi',
		'Bersi',
		'AcePharma',
		'AcePharma',
		'Samson International',
		'Samson International',
		'Famosan',
		'Famosan',
		'SOCO',
		'SOCO',
		'Lapis',
		'Lapis',
		'Relax',
		'Relax',
		'Hyalurmed',
		'Hyalurmed',
		'Alnatura',
		'Alnatura',
		'Medivet',
		'Medivet',
		'Otivet',
		'Otivet',
		'Benemedio',
		'Benemedio',
		'Expres menu',
		'Expres menu',
		'Oasis',
		'Oasis',
		'Floceta',
		'Floceta',
		'Silidyn',
		'Silidyn',
		'Carefree',
		'Carefree',
		'Pepino',
		'Pepino',
		'Schär',
		'Schär',
		'Megasol',
		'Megasol',
		'Ceria',
		'Ceria',
		'Erosgel',
		'Erosgel',
		'Stevikom',
		'Stevikom',
		'Wolfberry',
		'Wolfberry',
		'Doves Farm',
		'Doves Farm',
		'ES',
		'ES',
		'Vitana',
		'Vitana',
		'Afrin',
		'Afrin',
		'Kozlík',
		'Kozlík',
		'SerpensDerm',
		'SerpensDerm',
		'AQUAINT',
		'AQUAINT',
		'Extrudo',
		'Extrudo',
		'Ekoprodukt',
		'Ekoprodukt',
		'Combo',
		'Combo',
		'Pekkos',
		'Pekkos',
		'KLINGELE CHOCOLADE',
		'KLINGELE CHOCOLADE',
		'ZAMA',
		'ZAMA',
		'McLLOYD´S',
		'McLLOYD´S',
		'Brigit',
		'Brigit',
		'Bongo',
		'Bongo',
		'Barkat',
		'Barkat',
		'FIT',
		'FIT',
		'Octenidol',
		'Octenidol',
		'Alnavit',
		'Alnavit',
		'Alviana',
		'Alviana',
		'Depilan',
		'Depilan',
		'Optifibre',
		'Optifibre',
		'Revitalon',
		'Revitalon',
		'Skincode',
		'Skincode',
		'Purya!',
		'Purya!',
		'Silvanols',
		'Silvanols',
		'Elseve',
		'Elseve',
		'Suavipiel',
		'Suavipiel',
		'FerroFol-C MAMA',
		'FerroFol-C MAMA',
		'Englich Tea Shop',
		'Englich Tea Shop',
		'Dicloreum',
		'Dicloreum',
		'Erilens',
		'Erilens',
		'Curapor',
		'Curapor',
		'EasyGluco',
		'EasyGluco',
		'Corny',
		'Corny',
		'Fob test',
		'Fob test',
		'Racio',
		'Racio',
		'Promise',
		'Promise',
		'Optichamber',
		'Optichamber',
		'Herbalex',
		'Herbalex',
		'Silans',
		'Silans',
		'Dobica',
		'Dobica',
		'Contratubex',
		'Contratubex',
		'Imudon',
		'Imudon',
		'Petit Drill',
		'Petit Drill',
		'Prolacton',
		'Prolacton',
		'Nutricomp',
		'Nutricomp',
		'Gazin',
		'Gazin',
		'Perfektra',
		'Perfektra',
		'Figo',
		'Figo',
		'Rybilka',
		'Rybilka',
		'Steri',
		'Steri',
		'Sinupret',
		'Sinupret',
		'Acerumen',
		'Acerumen',
		'Omnifix',
		'Omnifix',
		'Fan Sladidla',
		'Fan Sladidla',
		'Nacho',
		'Nacho',
		'Puero',
		'Puero',
		'StreptoKill',
		'StreptoKill',
		'Rutinacea',
		'Rutinacea',
		'Supportan drink',
		'Supportan drink',
		'Trachisan',
		'Trachisan',
		'Hyiodine',
		'Hyiodine',
		'DebriEcaSan',
		'DebriEcaSan',
		'HyalEcaSan',
		'HyalEcaSan',
		'After Bite',
		'After Bite',
		'Amica',
		'Amica',
		'Mediplast',
		'Mediplast',
		'BASIC',
		'BASIC',
		'Orino',
		'Orino',
		'Hybler wipes',
		'Hybler wipes',
		'Safoco',
		'Safoco',
		'HydroFemin',
		'HydroFemin',
		'Halter',
		'Halter',
		'Hansaplast',
		'Hansaplast',
		'ALPRO',
		'ALPRO',
		'Odol',
		'Odol',
		'Rebi-Dental',
		'Rebi-Dental',
		'Rectostop',
		'Rectostop',
		'Mattes',
		'Mattes',
		'Luna',
		'Luna',
		'Baby Wipes',
		'Baby Wipes',
		'Anionlady',
		'Anionlady',
		'Calcident',
		'Calcident',
		'SÉRÉLYS',
		'SÉRÉLYS',
		'Clio',
		'Clio',
		'Maxi Nuta',
		'Maxi Nuta',
		'Energie',
		'Energie',
		'PharmaPoint',
		'PharmaPoint',
		'Unixderma',
		'Unixderma',
		'Tvaroháček',
		'Tvaroháček',
		'Panzynorm',
		'Panzynorm',
		'Mucoplant',
		'Mucoplant',
		'Big Bao',
		'Big Bao',
		'Epiderma',
		'Epiderma',
		'ASO',
		'ASO',
		'Dentibaby',
		'Dentibaby',
		'Enzymax',
		'Enzymax',
		'Similasan',
		'Similasan',
		'Big Soft',
		'Big Soft',
		'Aknepur',
		'Aknepur',
		'Zentrichova apatyka',
		'Zentrichova apatyka',
		'Cerustop',
		'Cerustop',
		'Coldises',
		'Coldises',
		'Krotolan',
		'Krotolan',
		'1Stepbiotest',
		'1Stepbiotest',
		'Ipsum Grade',
		'Ipsum Grade',
		'Woman Secret',
		'Woman Secret',
		'Acerola',
		'Acerola',
		'Cineol',
		'Cineol',
		'Sněhurka',
		'Sněhurka',
		'Cicatrix',
		'Cicatrix',
		'Symbi-lakt',
		'Symbi-lakt',
		'Merino',
		'Merino',
		'Medisk',
		'Medisk',
		'Bona Dea',
		'Bona Dea',
		'Nature\'s Voice',
		'Nature\'s Voice',
		'Himalaya',
		'Himalaya',
		'Acefill',
		'Acefill',
		'Ovocan',
		'Ovocan',
		'Belcura',
		'Belcura',
		'O´Tom',
		'O´Tom',
		'Lipoxal',
		'Lipoxal',
		'Medisign',
		'Medisign',
		'Erythritol',
		'Erythritol',
		'Voltaren',
		'Voltaren',
		'Gurmar',
		'Gurmar',
		'L-Tryptofan',
		'L-Tryptofan',
		'Maca Andina',
		'Maca Andina',
		'Gravimilk',
		'Gravimilk',
		'EZO',
		'EZO',
		'Juwital',
		'Juwital',
		'Lacto Lady',
		'Lacto Lady',
		'Pharma Progress',
		'Pharma Progress',
		'Hyson',
		'Hyson',
		'Advantage',
		'Advantage',
		'Green Pharmacy',
		'Green Pharmacy',
		'Pískavice',
		'Pískavice',
		'FertilCare',
		'FertilCare',
		'Coldamaris',
		'Coldamaris',
		'Renovality',
		'Renovality',
		'ActiMaris',
		'ActiMaris',
		'Drosetux',
		'Drosetux',
		'KlimaSei',
		'KlimaSei',
		'Clean&Clear',
		'Clean&Clear',
		'DiaVitamin',
		'DiaVitamin',
		'Proactivet',
		'Proactivet',
		'Eurocat',
		'Eurocat',
		'Swann Morton',
		'Swann Morton',
		'Ipsuum',
		'Ipsuum',
		'Complidermol',
		'Complidermol',
		'AND',
		'AND',
		'Biotter',
		'Biotter',
		'Oraflogo',
		'Oraflogo',
		'ArmoLipid',
		'ArmoLipid',
		'Stimulsin',
		'Stimulsin',
		'Epidond',
		'Epidond',
		'London Fruit Herb',
		'London Fruit Herb',
		'Flexodon',
		'Flexodon',
		'B17 Resveratrol',
		'B17 Resveratrol',
		'Babysense',
		'Babysense',
		'GYNIMUN',
		'GYNIMUN',
		'Benegen',
		'Benegen',
		'Ataxxa',
		'Ataxxa',
		'Origmed',
		'Origmed',
		'NeilMed',
		'NeilMed',
		'Flixonase',
		'Flixonase',
		'Ogestan',
		'Ogestan',
		'Femarelle',
		'Femarelle',
		'Ozonicon',
		'Ozonicon',
		'4Slim',
		'4Slim',
		'Inca',
		'Inca',
		'Lenor',
		'Lenor',
		'Astina',
		'Astina',
		'TheraPearl',
		'TheraPearl',
		'N848 Muay',
		'N848 Muay',
		'Veggie',
		'Veggie',
		'Ambrosan',
		'Ambrosan',
		'Aloe Vesta',
		'Aloe Vesta',
		'Zerostat VT',
		'Zerostat VT',
		'Freshness',
		'Freshness',
		'Bellawa',
		'Bellawa',
		'Raciolky',
		'Raciolky',
		'Inspirace',
		'Inspirace',
		'Kibodan',
		'Kibodan',
		'VšiVen',
		'VšiVen',
		'DL',
		'DL',
		'Vitto Vital',
		'Vitto Vital',
		'BMS Bohemian',
		'BMS Bohemian',
		'GKhair',
		'GKhair',
		'Revitality',
		'Revitality',
		'Happy',
		'Happy',
		'Dobexil-H',
		'Dobexil-H',
		'Simetistad',
		'Simetistad',
		'Maxivitalis',
		'Maxivitalis',
		'VIP',
		'VIP',
		'Probio',
		'Probio',
		'Kleenex',
		'Kleenex',
		'Kotex',
		'Kotex',
		'Advancis',
		'Advancis',
		'Swiss Vitamin D3',
		'Swiss Vitamin D3',
		'Jamasako',
		'Jamasako',
		'Anurex',
		'Anurex',
		'GlutenPrima',
		'GlutenPrima',
		'LaktoPrima',
		'LaktoPrima',
		'Antiped',
		'Antiped',
		'Pericil',
		'Pericil',
		'Carpathia',
		'Carpathia',
		'Natures Answer',
		'Natures Answer',
		'Medic',
		'Medic',
		'Oro Verde',
		'Oro Verde',
		'Dologran',
		'Dologran',
		'Dr. Schüsslera',
		'Dr. Schüsslera',
		'Otrivin',
		'Otrivin',
		'Zovirax',
		'Zovirax',
		'Duofilm',
		'Duofilm',
		'Flexitol',
		'Flexitol',
		'GlucoCare',
		'GlucoCare',
		'SETARIA',
		'SETARIA',
		'Zinkovit',
		'Zinkovit',
		'Super White',
		'Super White',
		'AVEWOMAN',
		'AVEWOMAN',
		'Kubatol',
		'Kubatol',
		'Klokan',
		'Klokan',
		'Caumed',
		'Caumed',
		'Benemedo',
		'Benemedo',
		'TOP DERM',
		'TOP DERM',
		'GUM Weawe',
		'GUM Weawe',
		'TANDEX',
		'TANDEX',
		'Phytoderma',
		'Phytoderma',
		'Profimed',
		'Profimed',
		'Mixa',
		'Mixa',
		'LUHA',
		'LUHA',
		'Venalin',
		'Venalin',
		'Ragina',
		'Ragina',
		'BELINE',
		'BELINE',
		'Cistibell',
		'Cistibell',
		'XXLABS',
		'XXLABS',
		'Herbal Harmony',
		'Herbal Harmony',
		'Alprose',
		'Alprose',
		'Carlotherm',
		'Carlotherm',
		'Skinsan',
		'Skinsan',
		'Biovitality',
		'Biovitality',
		'Petite Mars',
		'Petite Mars',
		'Fenistil',
		'Fenistil',
		'Gynella',
		'Gynella',
		'Benifuki',
		'Benifuki',
		'Atrix',
		'Atrix',
		'AnsCare',
		'AnsCare',
		'Re-Gen',
		'Re-Gen',
		'Topicrem',
		'Topicrem',
		'ProfiUro',
		'ProfiUro',
		'Belobaza',
		'Belobaza',
		'Celita',
		'Celita',
		'Sportovka',
		'Sportovka',
		'BioRepair',
		'BioRepair',
		'Jordan',
		'Jordan',
		'IMUREGEN',
		'IMUREGEN',
		'Bloom',
		'Bloom',
		'Nature\'s Life',
		'Nature\'s Life',
		'CANEPHRON',
		'CANEPHRON',
		'Cotoneve',
		'Cotoneve',
		'Manta',
		'Manta',
		'DIKOS',
		'DIKOS',
		'Hypro',
		'Hypro',
		'Milmar',
		'Milmar',
		'Reduxil',
		'Reduxil',
		'ATLET',
		'ATLET',
		'Acetocaustin',
		'Acetocaustin',
		'Sangrim',
		'Sangrim',
		'Monaco',
		'Monaco',
		'Livsane',
		'Livsane',
		'Mentos',
		'Mentos',
		'Virede',
		'Virede',
		'Hepatica',
		'Hepatica',
		'Melgisorb',
		'Melgisorb',
		'Xerostom',
		'Xerostom',
		'Mepilex',
		'Mepilex',
		'Bioaquanol',
		'Bioaquanol',
		'Air-lift',
		'Air-lift',
		'Mefix',
		'Mefix',
		'Pyrogenium',
		'Pyrogenium',
		'Kirkolina',
		'Kirkolina',
		'VA-BIOS',
		'VA-BIOS',
		'Vitamin D3 Oliva',
		'Vitamin D3 Oliva',
		'Dr.Fischer',
		'Dr.Fischer',
		'HANKE-SASS WOLF',
		'HANKE-SASS WOLF',
		'REPELAN',
		'REPELAN',
		'HerbActive',
		'HerbActive',
		'UrineScreen',
		'UrineScreen',
		'Rex',
		'Rex',
		'Easy Self Testing',
		'Easy Self Testing',
		'Sani-Cloth',
		'Sani-Cloth',
		'Medilona',
		'Medilona',
		'Giensan',
		'Giensan',
		'Helen Harper',
		'Helen Harper',
		'Reinex',
		'Reinex',
		'Fresh\'n Soft',
		'Fresh\'n Soft',
		'Arthoro',
		'Arthoro',
		'Rhino Horn',
		'Rhino Horn',
		'Sensuré',
		'Sensuré',
		'Silicea Magen',
		'Silicea Magen',
		'Septona',
		'Septona',
		'B Braun Medical',
		'B Braun Medical',
		'Vitto',
		'Vitto',
		'Protex',
		'Protex',
		'Normison',
		'Normison',
		'LiteTouch',
		'LiteTouch',
		'Astina Pharm',
		'Astina Pharm',
		'F&N',
		'F&N',
		'Erectan',
		'Erectan',
		'Viprolan',
		'Viprolan',
		'Spokar',
		'Spokar',
		'Schülke',
		'Schülke',
		'Davidoff',
		'Davidoff',
		'Tchibo',
		'Tchibo',
		'Collagen Extract',
		'Collagen Extract',
		'Chupa Chups',
		'Chupa Chups',
		'Codosil Adhesive',
		'Codosil Adhesive',
		'Perskindol',
		'Perskindol',
		'Biotrue',
		'Biotrue',
		'Fixovis',
		'Fixovis',
		'harmonic series',
		'harmonic series',
		'Ostropestřcový olej',
		'Ostropestřcový olej',
		'HerbExtract',
		'HerbExtract',
		'Polikosanol',
		'Polikosanol',
		'Vivaco',
		'Vivaco',
		'PferdeBalsam',
		'PferdeBalsam',
		'Herpago',
		'Herpago',
		'MicroalbuPhan',
		'MicroalbuPhan',
		'Beta glukan',
		'Beta glukan',
		'Juwík',
		'Juwík',
		'Mineral Beauty System',
		'Mineral Beauty System',
		'Elgydium',
		'Elgydium',
		'Grecian',
		'Grecian',
		'Pentron',
		'Pentron',
		'CardioWell',
		'CardioWell',
		'Audy',
		'Audy',
		'Bion 3',
		'Bion 3',
		'Natures Voice',
		'Natures Voice',
		'TrioRestart',
		'TrioRestart',
		'Formule VM',
		'Formule VM',
		'DL-Lecithin',
		'DL-Lecithin',
		'Mosi-guard',
		'Mosi-guard',
		'Laktáza',
		'Laktáza',
		'Smith & Nephew',
		'Smith & Nephew',
		'Diacoca',
		'Diacoca',
		'Forever Young',
		'Forever Young',
		'Peters Bestes',
		'Peters Bestes',
		'Vanesky',
		'Vanesky',
		'Velnesky',
		'Velnesky',
		'Pharma Bion',
		'Pharma Bion',
		'Queen Helene',
		'Queen Helene',
		'Alfalfa',
		'Alfalfa',
		'HEIDI',
		'HEIDI',
		'Arthronis',
		'Arthronis',
		'Multigreen',
		'Multigreen',
		'Mladý ječmen',
		'Mladý ječmen',
		'Thera-Band',
		'Thera-Band',
		'Van Cleef & Arples',
		'Van Cleef & Arples',
		'Carnitine',
		'Carnitine',
		'Tantum Natura',
		'Tantum Natura',
		'Rossmax',
		'Rossmax',
		'Milmex',
		'Milmex',
		'Blephagel',
		'Blephagel',
		'Emanace',
		'Emanace',
		'Vilcacora',
		'Vilcacora',
		'Sinecod',
		'Sinecod',
		'Ženšen',
		'Ženšen',
		'Anabox',
		'Anabox',
		'Nexcare',
		'Nexcare',
		'Ferrotone',
		'Ferrotone',
		'HERBAVER',
		'HERBAVER',
		'Momami',
		'Momami',
		'Grulich',
		'Grulich',
		'Heidel',
		'Heidel',
		'Exclusive chocolate',
		'Exclusive chocolate',
		'Nasaleze',
		'Nasaleze',
		'FUTURO',
		'FUTURO',
		'Girlz Only',
		'Girlz Only',
		'Tilman',
		'Tilman',
		'Venoruton',
		'Venoruton',
		'Vibrocil',
		'Vibrocil',
		'Theraflu',
		'Theraflu',
		'Apipharma',
		'Apipharma',
		'SuperBand',
		'SuperBand',
		'GUAa',
		'GUAa',
		'Alfa',
		'Alfa',
		'ProVenus',
		'ProVenus',
		'Carin',
		'Carin',
		'Horien',
		'Horien',
		'Swarowski',
		'Swarowski',
		'Widex',
		'Widex',
		'Dukas',
		'Dukas',
		'Onapharm',
		'Onapharm',
		'Divoká kosmetika',
		'Divoká kosmetika',
		'Hamé',
		'Hamé',
		'Plastin',
		'Plastin',
		'Biomycosin',
		'Biomycosin',
		'Power Band',
		'Power Band',
		'Manner',
		'Manner',
		'FertilCount',
		'FertilCount',
		'FertilCheck',
		'FertilCheck',
		'GAF',
		'GAF',
		'Curasept',
		'Curasept',
		'Ecosin',
		'Ecosin',
		'Aromedica',
		'Aromedica',
		'Kamill',
		'Kamill',
		'Beauty Mineral',
		'Beauty Mineral',
		'Mumiyo',
		'Mumiyo',
		'Stoddard',
		'Stoddard',
		'Dr. Fresh',
		'Dr. Fresh',
		'HEALTH INSTITUTE',
		'HEALTH INSTITUTE',
		'Walramcom',
		'Walramcom',
		'Eubos',
		'Eubos',
		'AET',
		'AET',
		'Intimea',
		'Intimea',
		'Kamil',
		'Kamil',
		'GRAV-IN',
		'GRAV-IN',
		'Betadent',
		'Betadent',
		'Laryguard',
		'Laryguard',
		'Betadnet',
		'Betadnet',
		'Pedro Perez',
		'Pedro Perez',
		'Sun&Sea',
		'Sun&Sea',
		'Banat',
		'Banat',
		'Purederm',
		'Purederm',
		'Skinanim',
		'Skinanim',
		'Sorbecta',
		'Sorbecta',
		'Bella',
		'Bella',
		'Veregin',
		'Veregin',
		'Visabell',
		'Visabell',
		'Ecce vita',
		'Ecce vita',
		'Tatramelky',
		'Tatramelky',
		'Superwhite',
		'Superwhite',
		'GVM I.E.',
		'GVM I.E.',
		'Questplast',
		'Questplast',
		'Herb extract',
		'Herb extract',
		'Diffusil',
		'Diffusil',
		'Utipro',
		'Utipro',
		'Comfort',
		'Comfort',
		'Achilon',
		'Achilon',
		'Top Green',
		'Top Green',
		'Life Light',
		'Life Light',
		'Inkospor',
		'Inkospor',
		'RedBlocker',
		'RedBlocker',
		'Parasoftin',
		'Parasoftin',
		'Natur-Sept',
		'Natur-Sept',
		'Enervit',
		'Enervit',
		'Jablotron',
		'Jablotron',
		'Renokin',
		'Renokin',
		'Oilatum',
		'Oilatum',
		'Panasonic',
		'Panasonic',
		'Délis',
		'Délis',
		'MiaCare',
		'MiaCare',
		'Cutimed',
		'Cutimed',
		'Risolino',
		'Risolino',
		'Baldriparan',
		'Baldriparan',
		'Naturica',
		'Naturica',
		'Ferimun',
		'Ferimun',
		'Capri Sonne',
		'Capri Sonne',
		'GelaVis',
		'GelaVis',
		'Halit',
		'Halit',
		'ColiPrev',
		'ColiPrev',
		'Micetal',
		'Micetal',
		'BioTec',
		'BioTec',
		'Červený',
		'Červený',
		'MaxiVita',
		'MaxiVita',
		'Domotherm',
		'Domotherm',
		'DOLCE&GABBANA',
		'DOLCE&GABBANA',
		'Lumene',
		'Lumene',
		'Milupa',
		'Milupa',
		'Loprofin',
		'Loprofin',
		'PEZ',
		'PEZ',
		'Loréal',
		'Loréal',
		'Krka',
		'Krka',
		'Bupi',
		'Bupi',
		'Zink',
		'Zink',
		'iWhite',
		'iWhite',
		'Elima',
		'Elima',
		'Alufix',
		'Alufix',
		'inPHARM',
		'inPHARM',
		'Curatest',
		'Curatest',
		'Ondrášovka',
		'Ondrášovka',
		'Suprasorb',
		'Suprasorb',
		'Pearl Drops',
		'Pearl Drops',
		'PHYTO',
		'PHYTO',
		'Dermatin',
		'Dermatin',
		'Spinbrush',
		'Spinbrush',
		'Fide',
		'Fide',
		'Dispogel',
		'Dispogel',
		'Devoré',
		'Devoré',
		'Haribo',
		'Haribo',
		'Casali',
		'Casali',
		'Cellona',
		'Cellona',
		'Joerex',
		'Joerex',
		'Sentina',
		'Sentina',
		'Media',
		'Media',
		'Mollelast',
		'Mollelast',
		'Sempercare',
		'Sempercare',
		'Rosidal',
		'Rosidal',
		'Curaplast',
		'Curaplast',
		'HPC',
		'HPC',
		'Intimohelp',
		'Intimohelp',
		'Porofix',
		'Porofix',
		'Haemolance',
		'Haemolance',
		'Dispolab',
		'Dispolab',
		'Soft next',
		'Soft next',
		'Balonix',
		'Balonix',
		'Sanitase',
		'Sanitase',
		'Kardio VS',
		'Kardio VS',
		'Argand\'Or',
		'Argand\'Or',
		'Schogetten',
		'Schogetten',
		'Fikar',
		'Fikar',
		'Stainless',
		'Stainless',
		'Ledragomma',
		'Ledragomma',
		'Ingremen',
		'Ingremen',
		'Simax',
		'Simax',
		'Software',
		'Software',
		'Unitop',
		'Unitop',
		'Tipson',
		'Tipson',
		'Cerea',
		'Cerea',
		'Classic Wheels',
		'Classic Wheels',
		'Thermofocus',
		'Thermofocus',
		'Basilur',
		'Basilur',
		'Visiofocus',
		'Visiofocus',
		'Achva',
		'Achva',
		'Pfanner',
		'Pfanner',
		'Sippah',
		'Sippah',
		'Seacare',
		'Seacare',
		'Ricky',
		'Ricky',
		'Meliseptol',
		'Meliseptol',
		'Softa-Man',
		'Softa-Man',
		'Tulips',
		'Tulips',
		'Sanity',
		'Sanity',
		'Optilets',
		'Optilets',
		'Sterican',
		'Sterican',
		'Kaumy',
		'Kaumy',
		'Promanum',
		'Promanum',
		'Softasept',
		'Softasept',
		'Amaryll',
		'Amaryll',
		'Injekt',
		'Injekt',
		'Ecolav',
		'Ecolav',
		'Phoenix Monopol',
		'Phoenix Monopol',
		'Timotei',
		'Timotei',
		'Imbio',
		'Imbio',
		'Tommee Tippee',
		'Tommee Tippee',
		'Nippon',
		'Nippon',
		'Eveline Cosmetics',
		'Eveline Cosmetics',
		'Desam',
		'Desam',
		'AQUASTERIL',
		'AQUASTERIL',
		'EYEYE',
		'EYEYE',
		'Chirox',
		'Chirox',
		'Natursept',
		'Natursept',
		'BIOLANE',
		'BIOLANE',
		'Nubian',
		'Nubian',
		'Ace Pharma',
		'Ace Pharma',
		'Carpathia Herbarium',
		'Carpathia Herbarium',
		'Balneo Trade Cosmetics',
		'Balneo Trade Cosmetics',
		'Oli',
		'Oli',
		'Magistr TOM',
		'Magistr TOM',
		'VARTA',
		'VARTA',
		'FYTO',
		'FYTO',
		'Vismed',
		'Vismed',
		'Naturix',
		'Naturix',
		'Slim Pasta',
		'Slim Pasta',
		'Respimer',
		'Respimer',
		'Slim Noodles',
		'Slim Noodles',
		'Decolen',
		'Decolen',
		'Slim Rice',
		'Slim Rice',
		'Green Line',
		'Green Line',
		'Milton',
		'Milton',
		'Prolab',
		'Prolab',
		'Quies',
		'Quies',
		'Tetesept',
		'Tetesept',
		'Amai',
		'Amai',
		'Dr Irena Eris',
		'Dr Irena Eris',
		'Ritex',
		'Ritex',
		'Tetesep',
		'Tetesep',
		'Vitalos',
		'Vitalos',
		'Kräuterhof',
		'Kräuterhof',
		'Herpetino',
		'Herpetino',
		'Dr. Vitto',
		'Dr. Vitto',
		'Hubdic',
		'Hubdic',
		'Les 3 Chénes',
		'Les 3 Chénes',
		'Your Days',
		'Your Days',
		'Cebelia',
		'Cebelia',
		'Essenté',
		'Essenté',
		'Pharma Line',
		'Pharma Line',
		'Keenwell',
		'Keenwell',
		'Curarina',
		'Curarina',
		'ES BIO',
		'ES BIO',
		'Pharmedis',
		'Pharmedis',
		'Alkavision',
		'Alkavision',
		'Motus',
		'Motus',
		'Spirularin',
		'Spirularin',
		'ABRA',
		'ABRA',
		'Coban',
		'Coban',
		'Accu-Chek',
		'Accu-Chek',
		'AeroChamber',
		'AeroChamber',
		'Ergon',
		'Ergon',
		'Agrogen',
		'Agrogen',
		'Arkokapsle',
		'Arkokapsle',
		'Asept',
		'Asept',
		'Artelac',
		'Artelac',
		'EpX',
		'EpX',
		'BABÉ',
		'BABÉ',
		'Rayovac',
		'Rayovac',
		'Splat',
		'Splat',
		'Béres',
		'Béres',
		'Burgit',
		'Burgit',
		'Bitusilky',
		'Bitusilky',
		'BiRetix',
		'BiRetix',
		'Cacicol',
		'Cacicol',
		'BlueFertil',
		'BlueFertil',
		'Biomin',
		'Biomin',
		'Carbo',
		'Carbo',
		'Cuticell',
		'Cuticell',
		'Cuida Te',
		'Cuida Te',
		'CUE',
		'CUE',
		'Dacom',
		'Dacom',
		'Deona',
		'Deona',
		'Tony Bennett',
		'Tony Bennett',
		'Virbac',
		'Virbac',
		'BlephaCura',
		'BlephaCura',
		'Mepiform',
		'Mepiform',
		'Sanofi',
		'Sanofi',
		'Replay',
		'Replay',
		'Cure Dents',
		'Cure Dents',
		'B.M.S.',
		'B.M.S.',
		'Gracie',
		'Gracie',
		'Golden Garden',
		'Golden Garden',
		'Em-Eukal',
		'Em-Eukal',
		'Magical Garden',
		'Magical Garden',
		'Evris',
		'Evris',
		'Vital',
		'Vital',
		'Ortomol',
		'Ortomol',
		'Hašlerky',
		'Hašlerky',
		'Sysex',
		'Sysex',
		'Jelly Bean',
		'Jelly Bean',
		'Heath & Heather',
		'Heath & Heather',
		'Dorset',
		'Dorset',
		'Silesse',
		'Silesse',
		'Gelita-Cel',
		'Gelita-Cel',
		'Diamonds',
		'Diamonds',
		'FreeStyle',
		'FreeStyle',
		'Sterilkompres',
		'Sterilkompres',
		'Glizigen',
		'Glizigen',
		'Genumedi',
		'Genumedi',
		'Granuflex',
		'Granuflex',
		'ConvaTec',
		'ConvaTec',
		'Herpatch Serum',
		'Herpatch Serum',
		'Heliocare',
		'Heliocare',
		'Maxsport',
		'Maxsport',
		'Abenu',
		'Abenu',
		'Pari Boy',
		'Pari Boy',
		'Isolda',
		'Isolda',
		'Owen Mumford',
		'Owen Mumford',
		'Artsana',
		'Artsana',
		'MTE',
		'MTE',
		'IVA',
		'IVA',
		'Ketocal',
		'Ketocal',
		'Silvercel',
		'Silvercel',
		'Debrisoft',
		'Debrisoft',
		'Mepitel',
		'Mepitel',
		'Vliwaktiv',
		'Vliwaktiv',
		'GlucoDr',
		'GlucoDr',
		'Lonaris',
		'Lonaris',
		'Cellacare',
		'Cellacare',
		'Leni COMPLEX',
		'Leni COMPLEX',
		'Lyzodol',
		'Lyzodol',
		'Maxiderma',
		'Maxiderma',
		'Lophlex',
		'Lophlex',
		'Vitaflo',
		'Vitaflo',
		'Mextra',
		'Mextra',
		'Micromed',
		'Micromed',
		'Karlovarské minerální vody',
		'Karlovarské minerální vody',
		'Opticlude',
		'Opticlude',
		'Mavala',
		'Mavala',
		'Orenzym',
		'Orenzym',
		'Curamedical',
		'Curamedical',
		'Detritin',
		'Detritin',
		'Merz',
		'Merz',
		'Natifem',
		'Natifem',
		'René Furterer',
		'René Furterer',
		'AD Calcis',
		'AD Calcis',
		'Fit-all',
		'Fit-all',
		'IBSA Farmaceutici Italia',
		'IBSA Farmaceutici Italia',
		'Vitakáva',
		'Vitakáva',
		'Melta',
		'Melta',
		'Fresubin',
		'Fresubin',
		'Bellasin',
		'Bellasin',
		'Dr. Weiss',
		'Dr. Weiss',
		'Endocare',
		'Endocare',
		'L-Mesitran',
		'L-Mesitran',
		'HayMax',
		'HayMax',
		'Memobiotic',
		'Memobiotic',
		'NeoRetin',
		'NeoRetin',
		'ACM Laboratoire Dermatologique',
		'ACM Laboratoire Dermatologique',
		'PainGone',
		'PainGone',
		'CAPSOLKA',
		'CAPSOLKA',
		'RUGARD Cosmetics',
		'RUGARD Cosmetics',
		'Veroval',
		'Veroval',
		'Meritene',
		'Meritene',
		'Capraverum Dog',
		'Capraverum Dog',
		'Capramilk',
		'Capramilk',
		'Capraverum Cat',
		'Capraverum Cat',
		'Nosifol',
		'Nosifol',
		'LaktoPlus',
		'LaktoPlus',
		'Bedegel',
		'Bedegel',
		'Vigantolvit',
		'Vigantolvit',
		'Dr. Böhm',
		'Dr. Böhm',
		'Lutein',
		'Lutein',
		'Radepur baby',
		'Radepur baby',
		'LepekFit',
		'LepekFit',
		'Resource',
		'Resource',
		'Bestier',
		'Bestier',
		'Herrens Mark',
		'Herrens Mark',
		'MaxiCor',
		'MaxiCor',
		'Women Secret',
		'Women Secret',
		'Ženšen FORTE',
		'Ženšen FORTE',
		'Grace',
		'Grace',
		'Dermibel',
		'Dermibel',
		'Algamaris',
		'Algamaris',
		'Nuevo Progreso',
		'Nuevo Progreso',
		'Survival',
		'Survival',
		'Dr.Staněk',
		'Dr.Staněk',
		'Folixil',
		'Folixil',
		'Astina KILOSTOP',
		'Astina KILOSTOP',
		'Astina MIGROSTOP',
		'Astina MIGROSTOP',
		'Paves',
		'Paves',
		'YANKEE CANDLE',
		'YANKEE CANDLE',
		'Walkers',
		'Walkers',
		'Apipol',
		'Apipol',
		'Reparil',
		'Reparil',
		'Regeneris',
		'Regeneris',
		'Extrifit',
		'Extrifit',
		'Canestest',
		'Canestest',
		'Hoodia',
		'Hoodia',
		'Gyntima',
		'Gyntima',
		'Prom-In',
		'Prom-In',
		'CRYOSFARMA',
		'CRYOSFARMA',
		'Concieve',
		'Concieve',
		'BAZA',
		'BAZA',
		'Merz Spezial',
		'Merz Spezial',
		'Artron',
		'Artron',
		'Apiprodent',
		'Apiprodent',
		'Salutem',
		'Salutem',
		'Livacare',
		'Livacare',
		'Matuzalem',
		'Matuzalem',
		'Boboscan',
		'Boboscan',
		'TRF',
		'TRF',
		'POSIFORLID',
		'POSIFORLID',
		'Becton Dickinson',
		'Becton Dickinson',
		'Trioderm Care',
		'Trioderm Care',
		'Parusan',
		'Parusan',
		'Chirana',
		'Chirana',
		'Prenatal',
		'Prenatal',
		'CERAVE',
		'CERAVE',
		'Dr.grepl',
		'Dr.grepl',
		'ONCLÉ',
		'ONCLÉ',
		'Black Storm',
		'Black Storm',
		'Dove',
		'Dove',
		'Rexona',
		'Rexona',
		'DrKonrad',
		'DrKonrad',
		'Pytheneo',
		'Pytheneo',
		'Stop',
		'Stop',
		'Détoxlim',
		'Détoxlim',
		'MoliCare',
		'MoliCare',
		'KIWU WUKI',
		'KIWU WUKI',
		'Neuroaspis',
		'Neuroaspis',
		'SOLAB',
		'SOLAB',
		'PSA Test',
		'PSA Test',
		'Biopron',
		'Biopron',
		'NYDA',
		'NYDA',
		'NefroPHAN',
		'NefroPHAN',
		'Stomax',
		'Stomax',
		'Dr.Maggie',
		'Dr.Maggie',
		'ChondroCat',
		'ChondroCat',
		'LA ROCHE- POSAY',
		'LA ROCHE- POSAY',
		'Luxury Fresh Smothie',
		'Luxury Fresh Smothie',
		'Luxury Fresh Smoothie',
		'Luxury Fresh Smoothie',
		'Luxury Fresh',
		'Luxury Fresh',
		'Orofar',
		'Orofar',
		'Hylak',
		'Hylak',
		'Labellino',
		'Labellino',
		'White Glo',
		'White Glo',
		'Namman Muay',
		'Namman Muay',
		'Nosko',
		'Nosko',
		'Proaura',
		'Proaura',
		'Psoricol',
		'Psoricol',
		'Pharma MKL',
		'Pharma MKL',
		'TrueLife',
		'TrueLife',
		'Actolind',
		'Actolind',
		'Landgarten',
		'Landgarten',
		'Boro',
		'Boro',
		'Laim',
		'Laim',
		'Reflex Nutrition',
		'Reflex Nutrition',
		'Gelone',
		'Gelone',
		'AQ Pure',
		'AQ Pure',
		'CooperVision',
		'CooperVision',
		'AOSEPT',
		'AOSEPT',
		'Menicon',
		'Menicon',
		'EnergyVet',
		'EnergyVet',
		'Astina Omega',
		'Astina Omega',
		'EYEREVIVE',
		'EYEREVIVE',
		'GlucoStep',
		'GlucoStep',
		'Hylo Dual',
		'Hylo Dual',
		'Kartalin',
		'Kartalin',
		'WADEX',
		'WADEX',
		'DMA',
		'DMA',
		'Nekadex',
		'Nekadex',
		'Questaplast',
		'Questaplast',
		'MenoRelax',
		'MenoRelax',
		'Meteospasmyl',
		'Meteospasmyl',
		'Nitricare',
		'Nitricare',
		'Nozitix',
		'Nozitix',
		'Active flora',
		'Active flora',
		'Tantogrip',
		'Tantogrip',
		'Dépiwhite',
		'Dépiwhite',
		'Dépiwhite.M',
		'Dépiwhite.M',
		'Metuzalem',
		'Metuzalem',
		'Health Culture',
		'Health Culture',
		'Litorsal',
		'Litorsal',
		'Gama Group',
		'Gama Group',
		'Specialist',
		'Specialist',
		'Oshun',
		'Oshun',
		'Olvizone',
		'Olvizone',
		'Odaban',
		'Odaban',
		'OROXID',
		'OROXID',
		'Ovocňák',
		'Ovocňák',
		'Optimal',
		'Optimal',
		'Ozal',
		'Ozal',
		'PARI Vortex',
		'PARI Vortex',
		'Epikond',
		'Epikond',
		'Perfect Dish',
		'Perfect Dish',
		'Pityzol',
		'Pityzol',
		'PinkFertil',
		'PinkFertil',
		'Revicord',
		'Revicord',
		'ProVens',
		'ProVens',
		'RadioXar',
		'RadioXar',
		'GeloSitin',
		'GeloSitin',
		'GeloRevoice',
		'GeloRevoice',
		'Sanoral',
		'Sanoral',
		'Revamil',
		'Revamil',
		'The BRAINER',
		'The BRAINER',
		'Redvel',
		'Redvel',
		'Rymanos',
		'Rymanos',
		'Bambo',
		'Bambo',
		'Medic Czech',
		'Medic Czech',
		'Saframyl',
		'Saframyl',
		'Sebogard',
		'Sebogard',
		'Spermotrend',
		'Spermotrend',
		'Sorelex',
		'Sorelex',
		'SPEED8',
		'SPEED8',
		'StomOdor',
		'StomOdor',
		'Reflex',
		'Reflex',
		'Tenoros',
		'Tenoros',
		'Vakcinal',
		'Vakcinal',
		'Vitarmonyl',
		'Vitarmonyl',
		'GingerParty',
		'GingerParty',
		'ZinOxid',
		'ZinOxid',
		'Karnitin chrom',
		'Karnitin chrom',
		'MyoTec',
		'MyoTec',
		'PharmaTheiss Cosmetics',
		'PharmaTheiss Cosmetics',
		'Paratizex',
		'Paratizex',
		'Tribitor',
		'Tribitor',
		'Dr.Weiss',
		'Dr.Weiss',
		'McCoy Teas',
		'McCoy Teas',
		'Miovarian',
		'Miovarian',
		'NervProtect',
		'NervProtect',
		'Dr.Light',
		'Dr.Light',
		'Dr.CBD',
		'Dr.CBD',
		'N-Medical',
		'N-Medical',
		'Bioline',
		'Bioline',
		'Eludril',
		'Eludril',
		'BetterYou',
		'BetterYou',
		'Biomedix',
		'Biomedix',
		'BIOMED',
		'BIOMED',
		'DIAS',
		'DIAS',
		'Lacto Seven',
		'Lacto Seven',
		'Lactovit',
		'Lactovit',
		'Dr. Konopka',
		'Dr. Konopka',
		'NextForce',
		'NextForce',
		'SD-CheckGOLD',
		'SD-CheckGOLD',
		'Ocurves',
		'Ocurves',
		'Ocuvers',
		'Ocuvers',
		'Menosan',
		'Menosan',
		'Gustée',
		'Gustée',
		'Toneye',
		'Toneye',
		'GS Condro',
		'GS Condro',
		'Rakytníček',
		'Rakytníček',
		'VENIRA',
		'VENIRA',
		'Herbofit',
		'Herbofit',
		'Dr. Popov',
		'Dr. Popov',
		'MoliMed',
		'MoliMed',
		'Klorane Bebe',
		'Klorane Bebe',
		'Klokare Bebe',
		'Klokare Bebe',
		'Flexiseq',
		'Flexiseq',
		'Fiorentini',
		'Fiorentini',
		'Molinea',
		'Molinea',
		'Mana',
		'Mana',
		'SwissMedicus',
		'SwissMedicus',
		'ColACTIN',
		'ColACTIN',
		'GO ON',
		'GO ON',
		'Asrtid',
		'Asrtid',
		'Forlax',
		'Forlax',
		'Meteo logic',
		'Meteo logic',
		'Salutem Pharma',
		'Salutem Pharma',
		'Cystiphane Biorga',
		'Cystiphane Biorga',
		'Janette',
		'Janette',
		'Soligen',
		'Soligen',
		'Endiaron',
		'Endiaron',
		'Allegra',
		'Allegra',
		'Productos Damel s. a.',
		'Productos Damel s. a.',
		'Alta Herba',
		'Alta Herba',
		'Natura Siberica',
		'Natura Siberica',
		'DonnaHAIR',
		'DonnaHAIR',
		'SINUPO',
		'SINUPO',
		'Erbenobili',
		'Erbenobili',
		'Bebutter',
		'Bebutter',
		'Solunate',
		'Solunate',
		'TraumaPet',
		'TraumaPet',
		'Dr.Candy',
		'Dr.Candy',
		'Libretto',
		'Libretto',
		'LOOQ',
		'LOOQ',
		'Speedees',
		'Speedees',
		'OptiCleaner',
		'OptiCleaner',
		'Uxitol',
		'Uxitol',
		'Apicold',
		'Apicold',
		'Jordan Step',
		'Jordan Step',
		'Penoxal',
		'Penoxal',
		'Tebodont',
		'Tebodont',
		'Tebolip',
		'Tebolip',
		'Protectum',
		'Protectum',
		'Twin Lotus',
		'Twin Lotus',
		'Hyal-Drop',
		'Hyal-Drop',
		'Gerimax',
		'Gerimax',
		'Mucodual',
		'Mucodual',
		'Oregano',
		'Oregano',
		'Fenjal',
		'Fenjal',
		'Dulcosoft',
		'Dulcosoft',
		'Kiwalin',
		'Kiwalin',
		'VoltaTherm',
		'VoltaTherm',
		'Oilesen',
		'Oilesen',
		'Vitabalans OY',
		'Vitabalans OY',
		'Cosmos',
		'Cosmos',
		'Vacutex',
		'Vacutex',
		'Crystal Fresh',
		'Crystal Fresh',
		'Boro Plus',
		'Boro Plus',
		'DR.SCHUMACHER',
		'DR.SCHUMACHER',
		'Aphrodisia',
		'Aphrodisia',
		'La Roche Posay',
		'La Roche Posay',
		'Intim',
		'Intim',
		'Formerco',
		'Formerco',
		'Lovi',
		'Lovi',
		'Charcoal',
		'Charcoal',
		'Lymphaveine',
		'Lymphaveine',
		'Advantix',
		'Advantix',
		'Hyaluron N',
		'Hyaluron N',
		'Hyaluron',
		'Hyaluron',
		'Hradzki',
		'Hradzki',
		'Bezkašel',
		'Bezkašel',
		'Sorbothane',
		'Sorbothane',
		'Lohmann&Rauscher',
		'Lohmann&Rauscher',
		'Medimento',
		'Medimento',
		'Depan',
		'Depan',
		'Long 4 Lashes',
		'Long 4 Lashes',
		'Belvas',
		'Belvas',
		'Tosama',
		'Tosama',
		'Brainway Inc.',
		'Brainway Inc.',
		'Ichthyo',
		'Ichthyo',
		'Hyalosan',
		'Hyalosan',
		'ProbioLact',
		'ProbioLact',
		'Masticlife',
		'Masticlife',
		'Neuraxpharm',
		'Neuraxpharm',
		'Tamsus',
		'Tamsus',
		'Johnsons',
		'Johnsons',
		'Capilarte',
		'Capilarte',
		'Orissa',
		'Orissa',
		'Diterpex',
		'Diterpex',
		'NutriSlim',
		'NutriSlim',
		'Johnson',
		'Johnson',
		'DOLORgit med',
		'DOLORgit med',
		'Bione',
		'Bione',
		'Vileda',
		'Vileda',
		'Baby-Nova',
		'Baby-Nova',
		'Amunak',
		'Amunak',
		'RosenPharma',
		'RosenPharma',
		'Cukrit',
		'Cukrit',
		'Bio Bione',
		'Bio Bione',
		'Kubík Waterrr',
		'Kubík Waterrr',
		'Kendamil',
		'Kendamil',
		'Link Natural',
		'Link Natural',
		'Preventan',
		'Preventan',
		'PharmaActiv',
		'PharmaActiv',
		'Svr',
		'Svr',
		'Zoosorb',
		'Zoosorb',
		'Syrovátka sušená',
		'Syrovátka sušená',
		'Micro Whey',
		'Micro Whey',
		'Puurex',
		'Puurex',
		'Babynol',
		'Babynol',
		'Samu',
		'Samu',
		'Therapy',
		'Therapy',
		'Alinan',
		'Alinan',
		'Bylinný repelent',
		'Bylinný repelent',
		'Ocuvite Lutein',
		'Ocuvite Lutein',
		'Drontal',
		'Drontal',
		'Kerasal',
		'Kerasal',
		'Medinatur',
		'Medinatur',
		'Relaxa',
		'Relaxa',
		'Eshederm',
		'Eshederm',
		'MinciNov',
		'MinciNov',
		'Sustenium',
		'Sustenium',
		'Hymalayo',
		'Hymalayo',
		'Sudorinal',
		'Sudorinal',
		'Bob´s',
		'Bob´s',
		'Burncare',
		'Burncare',
		'Pentaven',
		'Pentaven',
		'Matcha tea',
		'Matcha tea',
		'Fridababy',
		'Fridababy',
		'HiPP BABYSANFT',
		'HiPP BABYSANFT',
		'Healthlink',
		'Healthlink',
		'Valinka',
		'Valinka',
		'Prevomit',
		'Prevomit',
		'GreenPro',
		'GreenPro',
		'Diveen',
		'Diveen',
		'Kelapher',
		'Kelapher',
		'Virtue',
		'Virtue',
		'Pharmaton Geriavit',
		'Pharmaton Geriavit',
		'Valtix',
		'Valtix',
		'Geloren',
		'Geloren',
		'Olynth',
		'Olynth',
		'Vitalp',
		'Vitalp',
		'Allskin',
		'Allskin',
		'Oma Impex',
		'Oma Impex',
		'Nordic',
		'Nordic',
		'Hygienium',
		'Hygienium',
		'Australian Original',
		'Australian Original',
		'Pohádkový sirup',
		'Pohádkový sirup',
		'Tantum',
		'Tantum',
		'Carmex',
		'Carmex',
		'Zeropill',
		'Zeropill',
		'Femibion',
		'Femibion',
		'Navela',
		'Navela',
		'Česká alzheimerovská společnost',
		'Česká alzheimerovská společnost',
		'Joya',
		'Joya',
		'BulkySoft',
		'BulkySoft',
		'Majestic',
		'Majestic',
		'Nancyderm',
		'Nancyderm',
		'Arnika',
		'Arnika',
		'Detecha',
		'Detecha',
		'Riocarh',
		'Riocarh',
		'Riocath',
		'Riocath',
		'Travel',
		'Travel',
		'Nupreme',
		'Nupreme',
		'Gump',
		'Gump',
		'Eveine',
		'Eveine',
		'Dr. Browns',
		'Dr. Browns',
		'Pharmadis',
		'Pharmadis',
		'Fillerina',
		'Fillerina',
		'Fellerina',
		'Fellerina',
		'Crescina',
		'Crescina',
		'Gentle Day',
		'Gentle Day',
		'Cupper',
		'Cupper',
		'Bocoton',
		'Bocoton',
		'Ibument',
		'Ibument',
		'True Life',
		'True Life',
		'Vamousse',
		'Vamousse',
		'BlueM',
		'BlueM',
		'Dermikelp',
		'Dermikelp',
		'AnOxident balance',
		'AnOxident balance',
		'Solcoseryl',
		'Solcoseryl',
		'Otorig',
		'Otorig',
		'Idrozoil',
		'Idrozoil',
		'ErdoHerbal',
		'ErdoHerbal',
		'Procten',
		'Procten',
		'D-Tea',
		'D-Tea',
		'Gluneo',
		'Gluneo',
		'Droplet',
		'Droplet',
		'Element',
		'Element',
		'Simethicon',
		'Simethicon',
		'ClinSin',
		'ClinSin',
		'Blephademodex',
		'Blephademodex',
		'Helicid',
		'Helicid',
	];

}
