<?php declare(strict_types=1);

namespace App\ProductModule\Model\ExportToElastic;

class Categories
{

	public const VALUES = [
		'Léky na alergii',
		'Alergie - prášky, kapky, spreje',
		'První pomoc',
		'Speciální výživa',
		'Přípravky na svědění kůže a hlavy',
		'Léky na ekzémy a vyrážky',
		'Popraskaná a zrohovatělá kůže',
		'BENU ŽENÁM',
		'Ostatní výživa pro děti, kojence a batolata',
		'Léky na zažívání',
		'Přípravky na podporu trávení',
		'Léky na krevní oběh',
		'Léky na krevní sraženiny',
		'Krevní oběh a žíly',
		'Léky na kašel',
		'Kašel - sirupy, kapky, tablety',
		'Léčba chřipky',
		'Záněty',
		'Léky na migrény a bolesti hlavy',
		'Léky na horečku',
		'Léky na bolesti těla',
		'Menstruace - menstruační bolesti',
		'Chřipka a nachlazení',
		'Hlava',
		'Zuby',
		'Léky na posílení imunity',
		'Vitamíny',
		'Léky na otoky končetin',
		'Léky na křečové žíly',
		'Křeče',
		'Léky na hojení ran a jizev',
		'Léky na akné',
		'Akné',
		'Kapky do nosu',
		'Kapky do očí pro děti i dospělé',
		'Léky na svědění a záněty očí',
		'Oči',
		'Léky na krevní tlak',
		'Krevní tlak a cholesterol',
		'Sypané čaje',
		'Bylinné čaje',
		'Ostatní bylinky',
		'Léky na pálení žáhy',
		'Léky na překyselený žaludek',
		'Přípravky na pálení žáhy',
		'Žaludek',
		'Léky na bolesti svalů',
		'Svaly',
		'Záda',
		'Léky na bolesti kloubů',
		'Léky na artrózu',
		'Klouby a kloubní výživa',
		'Léky na rýmu',
		'Bylinné sirupy',
		'Kosti',
		'Léky na kožní plísně a vředy',
		'Mykóza - kožní, vaginální',
		'Léky na svědění a záněty pochvy',
		'Léky na průjem',
		'Průjem',
		'Imunita',
		'Léky na játra a žlučník',
		'Žlučník',
		'Bylinné kapky',
		'Léky na bolest v krku',
		'Rýma',
		'Léky na klouby',
		'Vánoční dárky',
		'Léky na deprese a stres',
		'Léky na spaní',
		'Přípravky na spaní',
		'Krk',
		'Antikoncepce',
		'Prostata a erekce',
		'Přípravky na erekci a prostatu',
		'Játra',
		'Hemoroidy - gely, krémy a masti',
		'Léky na hemoroidy',
		'Léky na zácpu',
		'Zácpa a projímadla',
		'Menopauza, klimakterium',
		'Léky na paměť',
		'Koncetrace a paměť',
		'Léky na závratě a točení hlavy',
		'Nervy a stres',
		'Bylinky na dýchací cesty',
		'Afty - přípravky pro léčbu',
		'Léky na opary a afty',
		'Dentální hygiena',
		'Opary - náplasti, masti, oleje',
		'Břicho',
		'Léky na afty',
		'Léky na křeče',
		'Klimakterium - Menopauza',
		'Znáte z TV',
		'Léky na odvykání kouření',
		'Léčba migrény',
		'Léky na obezitu',
		'Léky na popraskané koutky',
		'Koutky',
		'Léky proti zvracení a nevolnosti',
		'Léky na zánět močových cest a ledvin',
		'Bylinky na ledviny',
		'Bylinky na žaludek',
		'Bylinky na spaní',
		'Urologické čaje',
		'Dárky pro babičku a dědečka',
		'Náplasti a obvazy',
		'Inkontinenční vložky',
		'Inkontinence - pomůcky pro může i ženy',
		'Inkontinenční kalhotky',
		'Inkontinenční podložky',
		'Bylinky na krevní tlak',
		'Léky na popáleniny a opruzeniny',
		'Monokomponentní homeopatika',
		'Trávení, zažívání',
		'Dětské příkrmy',
		'Přípravky na ošetření kůže',
		'Doplňky stravy pro sportovce',
		'Kloubní výživa',
		'Fitness strava',
		'Péče o pleť',
		'Antiparazitika pro psy',
		'Antiparazitika pro kočky',
		'Péče o vlasy',
		'Vitamíny na imunitu pro děti',
		'Přípravky po bodnutí hmyzem',
		'Dětské krémy a masti',
		'Vlasy, kůže, nehty',
		'Energie a vitalita',
		'Doplňky stravy na imunitu',
		'Vitamíny na posílení imunity',
		'Opalování - krémy, mléka, spreje a další',
		'Péče o tělo - dermokosmetika',
		'Dermokosmetika na opalování',
		'Žíly a krevní oběh',
		'Bylinky na hubnutí',
		'Přípravky a prášky na hubnutí',
		'Antiperspiranty a deodoranty',
		'Péče o pleť - dermokosmetika',
		'Bělení zubů',
		'Zubní pasty',
		'Dětská kosmetika',
		'Dětské šampony a mýdla',
		'Ústní vody',
		'Laktobacily',
		'Probiotika',
		'Péče o nohy',
		'Prezervativy',
		'Kondomy',
		'Dýchací soustava',
		'Ostatní vitamíny',
		'Ostatní minerály',
		'Ostatní doplňky stravy',
		'Přípravky na strie',
		'Kůže - Kožní potíže',
		'Hořčík (magnesium)  - Minerály',
		'Kosmetika na léto',
		'Dětské nápoje',
		'Kosmetika pro těhotné',
		'Péče o tělo',
		'Kapky do očí',
		'Kaše pro děti a kojence',
		'Valentýnské tipy',
		'Péče o vlasy - dermokosmetika',
		'Péče o ruce',
		'Vložky',
		'Zelené čaje',
		'Ovocné čaje',
		'Spánek - Doplňky stravy',
		'Bylinky na posílení imunity',
		'Močové cesty',
		'Doplňky stravy na klimakterium',
		'Ledviny a močový měchýř',
		'Erekce a prostata',
		'Výživa při kojení',
		'Dětské čaje',
		'Dětské vlhčené ubrousky',
		'Roztoky na kontaktní čočky',
		'Čaje pro těhotné',
		'Kojenecká mléka',
		'Paměť a koncentrace',
		'Regenerace a masáže',
		'Krémy a masti pro sportovce',
		'Back to school',
		'Čaje na hubnutí',
		'Detoxikace',
		'Multivitamíny',
		'Polykomponentní homeopatika',
		'Repelenty',
		'Přípravky proti hmyzu',
		'Dezinfekce',
		'Dudlíky a šidítka',
		'Tlakoměry',
		'Uši - spreje, kapky, oleje a svíčky',
		'Vatové tyčinky',
		'Ostatní dětská kosmetika',
		'Přípravky a masti na hemoroidy',
		'Náplasti',
		'Černé čaje',
		'Detoxikační čaje',
		'Dětská výživa',
		'Vitamíny a minerály pro děti',
		'Laktobacily pro děti',
		'Lubrikační gely',
		'Opalovací krémy pro kojence',
		'Výživa batolat',
		'Zubní a mezizubní kartáčky',
		'Výživa a vitamíny pro těhotné',
		'Vitamíny pro těhotné a kojící',
		'Minerály',
		'Mezizubní kartáčky a dentální nitě',
		'Prsní kloboučky a vložky do podprsenky',
		'Omega kyseliny',
		'Doplňky stravy',
		'Bylinky na krk',
		'Vitamíny při kojení',
		'Přípravky do koupele',
		'Vaginální čípky a tablety',
		'Antiperspiranty a deodoranty - dermokosmetické',
		'Přípravky na bradavice a kuří oka',
		'Doplňky stravy na oči',
		'Polévky pro děti',
		'Dětské kartáčky a zubní pasty',
		'Intimní přípravky',
		'Dětské láhve',
		'Přípravky na ošetření popálenin',
		'Kojenecké láhve a lahvičky',
		'Dia sladidla a medy',
		'Sladidla',
		'Vitamíny pro seniory',
		'Bylinky na odvodnění',
		'Multivitamíny pro děti',
		'Autolékárnička',
		'Antioxidanty',
		'Ostatní bezlepková výživa',
		'Sušenky a křupky',
		'Péče o zubní protézu',
		'Vitamíny na klouby',
		'Gelové, chladivé polštářky',
		'Železo - Minerály',
		'Inkontinenční pomůcky',
		'Dárky pro ženy',
		'Dárky pro muže',
		'Dětské přebalovací podložky',
		'Dětské teploměry',
		'Digitální teploměry',
		'Dárky pro děti',
		'Hračky',
		'Těhotenské testy pro ženy',
		'Těhotenské testy',
		'Zubní hygiena',
		'Superfoods - superpotraviny',
		'Iontové nápoje',
		'Minerály pro děti',
		'Nukleotidy',
		'Zinek - Minerály',
		'Nápoje',
		'Manikúra',
		'Vápník (calcium) - Minerály',
		'Ortopedické bandáže a ortézy',
		'Ortopedické pásy a rovnače zad',
		'Výprodej',
		'Doplňky stravy pro psy',
		'Chovatelské potřeby pro psy',
		'Vitamíny pro psy',
		'Vitamíny pro oči',
		'Intimní vlhčené ubrousky a kapesníčky',
		'Ostatní zdravá výživa',
		'Vaginální mykóza',
		'Dětské odsávačky hlenů',
		'Bezlepkové nápoje',
		'Instantní nápoje',
		'Pochutiny',
		'Plíseň a mykóza nehtů',
		'Kožní mykóza',
		'Tejpy',
		'Bezkontaktní teploměry',
		'Obsah lékárničky',
		'Bílé čaje',
		'Vředy',
		'Bio oleje',
		'Vody',
		'Ostatní dietní výživa',
		'Výživa pro sportovce',
		'Chrániče sluchu',
		'Doplňky stravy pro kočky',
		'Bezlepkové cereálie a kaše',
		'Dávkovače léků',
		'Chrom - Minerály',
		'Dětské pleny',
		'Šťávy a sirupy',
		'Spalovač tuků',
		'Sportovní nápoje',
		'Výživa nehtů',
		'Tampóny a menstruační kalíšky',
		'Ovulační testy pro ženy',
		'Ovulační testy',
		'Pinzety',
		'Dietní tyčinky a sušenky',
		'Tyčinky',
		'Odsávačky mléka',
		'Kaše',
		'Dietní nápoje',
		'Aminokyseliny',
		'Draslík - Minerály',
		'Karbohydráty',
		'Skleněné teploměry',
		'Vata',
		'Ústní sprchy a spreje',
		'Kloubní výživa pro psy',
		'Vložky do bot',
		'BIO nápoje',
		'Laky na nehty',
		'Injekční stříkačky',
		'Papírové kapesníčky',
		'Dárkové sety',
		'Bezlepkový chléb a mouka',
		'Chléb',
		'Domácí lékárnička',
		'Podpatěnky, korektory nohou',
		'Šťítná žláza',
		'Přípravky na detoxikaci organismu',
		'Ostatní diagnostické testy',
		'Rostlinné nápoje',
		'Přírodní nápoje',
		'Glukometry',
		'Bylinky na erekci',
		'Rukavice a čepice',
		'Testy na drogy',
		'Sušené ovoce',
		'Medy',
		'Ústní roušky a ústěnky',
		'Na holení',
		'Sacharidy',
		'Bezlepkové tyčinky a sušenky',
		'Musli tyčinky',
		'Uchování mateřského mléka',
		'Superfoods',
		'Zdravotní punčochy a ponožky',
		'Lékárnička na pracoviště',
		'Po holení',
		'Parfémy',
		'Testy na cukrovku',
		'Bolest kolen',
		'Dietní Superfoods',
		'BIO superfoods',
		'Hygienické ubrousky a utěrky',
		'Ostatní BIO výživa',
		'Proteiny',
		'Lékárnička na cesty, dovolenou',
		'Krmivo a granule pro psy',
		'Dětské chůvičky a monitory dechu',
		'Inhalátory a nástavce',
		'Bezlepkové těstoviny',
		'Sušenky',
		'Masážní pomůcky',
		'Holící strojky a žiletky',
		'Ostatní zdravotnické pomůcky',
		'Ohřívače lahví',
		'Osobní váhy',
		'Ostatní kojenecké potřeby',
		'Krémy',
		'Inkontinenční pleny',
		'Vitamíny na pleť',
		'Vitamíny na nehty',
		'Inzulínová pera',
		'Intimní testy, testy plodnosti',
		'Přípravky na kuří oka',
		'Odličovací tampony',
		'Pomůcky do koupelny, WC',
		'Krokoměry, elektrostimulátory, masážní přístroje',
		'Sterilizátory',
		'Ortopedické vložky do bot',
		'BIO šťávy',
		'Chovatelské potřeby pro kočky',
		'Vodítka a obojky pro psy',
		'Chovatelské potřeby pro ostatní zvířata',
		'Bandáže',
		'Cereálie',
		'Ostatní potřeby pro hlodavce',
		'Bezlepkové sušené ovoce a ořechy',
		'Tejpy, bandáže a náplasti',
		'Léky na nehty',
		'Náplasti na bradavice a kuří oka',
		'Káva a náhražky kávy',
		'Semena',
		'BIO tyčinky a sušenky',
		'BIO sladidla a medy',
		'BIO cereálie a kaše',
		'Dietní cereálie a kaše',
		'Ořechy',
		'Dietní chléb a mouka',
		'Mouka',
		'BIO sušené ovoce a ořechy',
		'BIO chléb a mouka',
		'Bezlepkové potraviny',
		'Vosk na depilaci',
		'Podpora a posílení erekce',
		'BIO semena a luštěniny',
		'Ortopedické berle a hole',
		'Berle a hole',
		'Krémy na intimní partie',
		'Toaletní papír',
		'Ortopedické pásy',
		'Lékařské nástroje',
		'Tělová mléka',
		'Oleje',
		'Léky na bradavice a kuří oka',
		'Vitamíny pro kočky',
		'Kalíšky',
		'Léky na inkontinenci',
		'Dětské zubní pasty',
		'Energetické gely',
		'Balzámy',
		'Léky na brnění končetin',
		'Mýdla',
		'Ortopedické polštáře',
		'II. jakost',
		'Injekční jehly',
		'Dietní semena a luštěniny',
		'Homeopatika',
		'CRP testy',
		'Luštěniny',
		'Teploměry',
		'Testy na alkohol',
	];

}
